apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "oxia-cluster.coordinator.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-coordinator
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
  - name: {{ .Values.imagePullSecrets }}
{{- end}}
