apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "oxia-cluster.coordinator.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-coordinator
data:
  config.yaml: |
    initialShardCount: {{ .Values.initialShardCount }}
    replicationFactor: {{ .Values.replicationFactor }}
    servers:
      {{- $vars := dict "name" .Release.Name "namespace" .Release.Namespace "public" .Values.server.ports.public "internal" .Values.server.ports.internal }}
      {{- range until (int .Values.server.replicas) }}
      - public: {{ $vars.name }}-{{ . }}.{{ $vars.name }}.{{ $vars.namespace }}.svc.cluster.local:{{ $vars.public }}
        internal: {{ $vars.name }}-{{ . }}.{{ $vars.name }}.{{ $vars.namespace }}.svc.cluster.local:{{ $vars.internal }}
      {{- end }}
