apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "oxia-cluster.coordinator.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-coordinator
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "*" ]
  - apiGroups: [ "oxia.streamnative.io" ]
    resources: [ "oxiaclusters" ]
    verbs: [ "get", "update" ]
