apiVersion: v1
kind: Service
metadata:
  labels:
    oxia_cluster: {{ .Release.Name }}
    {{- include "oxia-cluster.server.labels" . | nindent 4 }}
  name: {{ .Release.Name }}
spec:
  clusterIP: None
  ports:
    {{- range $key, $value := .Values.server.ports }}
    - name: {{ $key }}
      port: {{ $value }}
      targetPort: {{ $key }}
    {{- end}}
  selector:
    {{- include "oxia-cluster.server.selectorLabels" . | nindent 4 }}
