apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "oxia-controller.labels" . | nindent 4 }}
  name: {{ .Release.Name }}
spec:
  ports:
    {{- range $key, $value := .Values.ports }}
    - name: {{ $key }}
      port: {{ $value }}
      targetPort: {{ $key }}
    {{- end}}
  selector:
    {{- include "oxia-controller.selectorLabels" . | nindent 4 }}
