apiVersion: oxia.streamnative.io/v1alpha1
kind: OxiaCluster
metadata:
  labels:
    app.kubernetes.io/name: oxiacluster
    app.kubernetes.io/instance: oxiacluster-sample
    app.kubernetes.io/part-of: oxia-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: oxia-operator
  name: test-oxia
  namespace: oxia

spec:
  namespaces:
    - name: default
      initialShardCount: 3
      replicationFactor: 3
  
  coordinator:
    cpu: 400m
    memory: 256Mi
  server:
    replicas: 4
    cpu: 1000m
    memory: 1Gi
    storage: 100Gi
    # storageClassName: sn-ssd
  image:
    repository: oxia
    tag: latest
    pullPolicy: Never
  #    pullSecrets: my-docker-secret
  monitoringEnabled: true
  pprofEnabled: true
