apiVersion: apps/v1
kind: Deployment
metadata:
  name: perf-client
  labels:
    app: perf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perf
  template:
    metadata:
          labels:
            app: perf
    spec:
      containers:
      - name: perf
        image: streamnative/oxia:main
        command: ["oxia"]
        args: ["perf", "-a", "oxia-svc.oxia.svc.cluster.local:6648", "-n", "default", "-r", "100", "--keys-cardinality", "1000"]
          
