# Default values for oxia-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#imagePullSecrets: oxia

image:
  repository: oxia
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

resources:
  cpu: 100m
  memory: 128Mi

ports:
  internal: 6649
  metrics: 8080

serviceMonitor: false
