// Copyright 2023-2025 The Oxia Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//*
// Oxia Coordinator Admin API

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: admin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OxiaAdmin_ListDataServers_FullMethodName  = "/io.oxia.proto.v1.OxiaAdmin/ListDataServers"
	OxiaAdmin_GetDataServer_FullMethodName    = "/io.oxia.proto.v1.OxiaAdmin/GetDataServer"
	OxiaAdmin_CreateDataServer_FullMethodName = "/io.oxia.proto.v1.OxiaAdmin/CreateDataServer"
	OxiaAdmin_ListNamespaces_FullMethodName   = "/io.oxia.proto.v1.OxiaAdmin/ListNamespaces"
	OxiaAdmin_ListNodes_FullMethodName        = "/io.oxia.proto.v1.OxiaAdmin/ListNodes"
	OxiaAdmin_SplitShard_FullMethodName       = "/io.oxia.proto.v1.OxiaAdmin/SplitShard"
)

// OxiaAdminClient is the client API for OxiaAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OxiaAdminClient interface {
	ListDataServers(ctx context.Context, in *ListDataServersRequest, opts ...grpc.CallOption) (*ListDataServersResponse, error)
	GetDataServer(ctx context.Context, in *GetDataServerRequest, opts ...grpc.CallOption) (*GetDataServerResponse, error)
	CreateDataServer(ctx context.Context, in *CreateDataServerRequest, opts ...grpc.CallOption) (*CreateDataServerResponse, error)
	ListNamespaces(ctx context.Context, in *ListNamespacesRequest, opts ...grpc.CallOption) (*ListNamespacesResponse, error)
	// Deprecated: Use ListDataServers instead.
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
	// *
	// Triggers a shard split. The specified shard is split into two child
	// shards at the given split point (or midpoint if not specified).
	SplitShard(ctx context.Context, in *SplitShardRequest, opts ...grpc.CallOption) (*SplitShardResponse, error)
}

type oxiaAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewOxiaAdminClient(cc grpc.ClientConnInterface) OxiaAdminClient {
	return &oxiaAdminClient{cc}
}

func (c *oxiaAdminClient) ListDataServers(ctx context.Context, in *ListDataServersRequest, opts ...grpc.CallOption) (*ListDataServersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDataServersResponse)
	err := c.cc.Invoke(ctx, OxiaAdmin_ListDataServers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oxiaAdminClient) GetDataServer(ctx context.Context, in *GetDataServerRequest, opts ...grpc.CallOption) (*GetDataServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDataServerResponse)
	err := c.cc.Invoke(ctx, OxiaAdmin_GetDataServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oxiaAdminClient) CreateDataServer(ctx context.Context, in *CreateDataServerRequest, opts ...grpc.CallOption) (*CreateDataServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDataServerResponse)
	err := c.cc.Invoke(ctx, OxiaAdmin_CreateDataServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oxiaAdminClient) ListNamespaces(ctx context.Context, in *ListNamespacesRequest, opts ...grpc.CallOption) (*ListNamespacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNamespacesResponse)
	err := c.cc.Invoke(ctx, OxiaAdmin_ListNamespaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oxiaAdminClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, OxiaAdmin_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oxiaAdminClient) SplitShard(ctx context.Context, in *SplitShardRequest, opts ...grpc.CallOption) (*SplitShardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SplitShardResponse)
	err := c.cc.Invoke(ctx, OxiaAdmin_SplitShard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OxiaAdminServer is the server API for OxiaAdmin service.
// All implementations must embed UnimplementedOxiaAdminServer
// for forward compatibility.
type OxiaAdminServer interface {
	ListDataServers(context.Context, *ListDataServersRequest) (*ListDataServersResponse, error)
	GetDataServer(context.Context, *GetDataServerRequest) (*GetDataServerResponse, error)
	CreateDataServer(context.Context, *CreateDataServerRequest) (*CreateDataServerResponse, error)
	ListNamespaces(context.Context, *ListNamespacesRequest) (*ListNamespacesResponse, error)
	// Deprecated: Use ListDataServers instead.
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	// *
	// Triggers a shard split. The specified shard is split into two child
	// shards at the given split point (or midpoint if not specified).
	SplitShard(context.Context, *SplitShardRequest) (*SplitShardResponse, error)
	mustEmbedUnimplementedOxiaAdminServer()
}

// UnimplementedOxiaAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOxiaAdminServer struct{}

func (UnimplementedOxiaAdminServer) ListDataServers(context.Context, *ListDataServersRequest) (*ListDataServersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDataServers not implemented")
}
func (UnimplementedOxiaAdminServer) GetDataServer(context.Context, *GetDataServerRequest) (*GetDataServerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDataServer not implemented")
}
func (UnimplementedOxiaAdminServer) CreateDataServer(context.Context, *CreateDataServerRequest) (*CreateDataServerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDataServer not implemented")
}
func (UnimplementedOxiaAdminServer) ListNamespaces(context.Context, *ListNamespacesRequest) (*ListNamespacesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNamespaces not implemented")
}
func (UnimplementedOxiaAdminServer) ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedOxiaAdminServer) SplitShard(context.Context, *SplitShardRequest) (*SplitShardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SplitShard not implemented")
}
func (UnimplementedOxiaAdminServer) mustEmbedUnimplementedOxiaAdminServer() {}
func (UnimplementedOxiaAdminServer) testEmbeddedByValue()                   {}

// UnsafeOxiaAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OxiaAdminServer will
// result in compilation errors.
type UnsafeOxiaAdminServer interface {
	mustEmbedUnimplementedOxiaAdminServer()
}

func RegisterOxiaAdminServer(s grpc.ServiceRegistrar, srv OxiaAdminServer) {
	// If the following call panics, it indicates UnimplementedOxiaAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OxiaAdmin_ServiceDesc, srv)
}

func _OxiaAdmin_ListDataServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDataServersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OxiaAdminServer).ListDataServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OxiaAdmin_ListDataServers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OxiaAdminServer).ListDataServers(ctx, req.(*ListDataServersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OxiaAdmin_GetDataServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OxiaAdminServer).GetDataServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OxiaAdmin_GetDataServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OxiaAdminServer).GetDataServer(ctx, req.(*GetDataServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OxiaAdmin_CreateDataServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDataServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OxiaAdminServer).CreateDataServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OxiaAdmin_CreateDataServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OxiaAdminServer).CreateDataServer(ctx, req.(*CreateDataServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OxiaAdmin_ListNamespaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNamespacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OxiaAdminServer).ListNamespaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OxiaAdmin_ListNamespaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OxiaAdminServer).ListNamespaces(ctx, req.(*ListNamespacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OxiaAdmin_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OxiaAdminServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OxiaAdmin_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OxiaAdminServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OxiaAdmin_SplitShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SplitShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OxiaAdminServer).SplitShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OxiaAdmin_SplitShard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OxiaAdminServer).SplitShard(ctx, req.(*SplitShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OxiaAdmin_ServiceDesc is the grpc.ServiceDesc for OxiaAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OxiaAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "io.oxia.proto.v1.OxiaAdmin",
	HandlerType: (*OxiaAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDataServers",
			Handler:    _OxiaAdmin_ListDataServers_Handler,
		},
		{
			MethodName: "GetDataServer",
			Handler:    _OxiaAdmin_GetDataServer_Handler,
		},
		{
			MethodName: "CreateDataServer",
			Handler:    _OxiaAdmin_CreateDataServer_Handler,
		},
		{
			MethodName: "ListNamespaces",
			Handler:    _OxiaAdmin_ListNamespaces_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _OxiaAdmin_ListNodes_Handler,
		},
		{
			MethodName: "SplitShard",
			Handler:    _OxiaAdmin_SplitShard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin.proto",
}
