// Copyright 2023-2025 The Oxia Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//*
// Oxia Coordinator Admin API

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: admin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OxiaAdmin_ListDataServers_FullMethodName    = "/io.oxia.proto.v1.OxiaAdmin/ListDataServers"
	OxiaAdmin_GetDataServer_FullMethodName      = "/io.oxia.proto.v1.OxiaAdmin/GetDataServer"
	OxiaAdmin_CreateDataServer_FullMethodName   = "/io.oxia.proto.v1.OxiaAdmin/CreateDataServer"
	OxiaAdmin_PatchDataServer_FullMethodName    = "/io.oxia.proto.v1.OxiaAdmin/PatchDataServer"
	OxiaAdmin_DeleteDataServer_FullMethodName   = "/io.oxia.proto.v1.OxiaAdmin/DeleteDataServer"
	OxiaAdmin_CreateNamespace_FullMethodName    = "/io.oxia.proto.v1.OxiaAdmin/CreateNamespace"
	OxiaAdmin_PatchNamespace_FullMethodName     = "/io.oxia.proto.v1.OxiaAdmin/PatchNamespace"
	OxiaAdmin_DeleteNamespace_FullMethodName    = "/io.oxia.proto.v1.OxiaAdmin/DeleteNamespace"
	OxiaAdmin_GetNamespace_FullMethodName       = "/io.oxia.proto.v1.OxiaAdmin/GetNamespace"
	OxiaAdmin_ListNamespaces_FullMethodName     = "/io.oxia.proto.v1.OxiaAdmin/ListNamespaces"
	OxiaAdmin_GetClusterPolicy_FullMethodName   = "/io.oxia.proto.v1.OxiaAdmin/GetClusterPolicy"
	OxiaAdmin_PatchClusterPolicy_FullMethodName = "/io.oxia.proto.v1.OxiaAdmin/PatchClusterPolicy"
	OxiaAdmin_SplitShard_FullMethodName         = "/io.oxia.proto.v1.OxiaAdmin/SplitShard"
)

// OxiaAdminClient is the client API for OxiaAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OxiaAdminClient interface {
	ListDataServers(ctx context.Context, in *ListDataServersRequest, opts ...grpc.CallOption) (*ListDataServersResponse, error)
	GetDataServer(ctx context.Context, in *GetDataServerRequest, opts ...grpc.CallOption) (*GetDataServerResponse, error)
	CreateDataServer(ctx context.Context, in *CreateDataServerRequest, opts ...grpc.CallOption) (*CreateDataServerResponse, error)
	PatchDataServer(ctx context.Context, in *PatchDataServerRequest, opts ...grpc.CallOption) (*PatchDataServerResponse, error)
	DeleteDataServer(ctx context.Context, in *DeleteDataServerRequest, opts ...grpc.CallOption) (*DeleteDataServerResponse, error)
	CreateNamespace(ctx context.Context, in *CreateNamespaceRequest, opts ...grpc.CallOption) (*CreateNamespaceResponse, error)
	PatchNamespace(ctx context.Context, in *PatchNamespaceRequest, opts ...grpc.CallOption) (*PatchNamespaceResponse, error)
	DeleteNamespace(ctx context.Context, in *DeleteNamespaceRequest, opts ...grpc.CallOption) (*DeleteNamespaceResponse, error)
	GetNamespace(ctx context.Context, in *GetNamespaceRequest, opts ...grpc.CallOption) (*GetNamespaceResponse, error)
	ListNamespaces(ctx context.Context, in *ListNamespacesRequest, opts ...grpc.CallOption) (*ListNamespacesResponse, error)
	GetClusterPolicy(ctx context.Context, in *GetClusterPolicyRequest, opts ...grpc.CallOption) (*GetClusterPolicyResponse, error)
	PatchClusterPolicy(ctx context.Context, in *PatchClusterPolicyRequest, opts ...grpc.CallOption) (*PatchClusterPolicyResponse, error)
	// *
	// Triggers a shard split. The specified shard is split into two child
	// shards at the given split point (or midpoint if not specified).
	SplitShard(ctx context.Context, in *SplitShardRequest, opts ...grpc.CallOption) (*SplitShardResponse, error)
}

type oxiaAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewOxiaAdminClient(cc grpc.ClientConnInterface) OxiaAdminClient {
	return &oxiaAdminClient{cc}
}

func (c *oxiaAdminClient) ListDataServers(ctx context.Context, in *ListDataServersRequest, opts ...grpc.CallOption) (*ListDataServersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDataServersResponse)
	err := c.cc.Invoke(ctx, OxiaAdmin_ListDataServers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oxiaAdminClient) GetDataServer(ctx context.Context, in *GetDataServerRequest, opts ...grpc.CallOption) (*GetDataServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDataServerResponse)
	err := c.cc.Invoke(ctx, OxiaAdmin_GetDataServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oxiaAdminClient) CreateDataServer(ctx context.Context, in *CreateDataServerRequest, opts ...grpc.CallOption) (*CreateDataServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDataServerResponse)
	err := c.cc.Invoke(ctx, OxiaAdmin_CreateDataServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oxiaAdminClient) PatchDataServer(ctx context.Context, in *PatchDataServerRequest, opts ...grpc.CallOption) (*PatchDataServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PatchDataServerResponse)
	err := c.cc.Invoke(ctx, OxiaAdmin_PatchDataServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oxiaAdminClient) DeleteDataServer(ctx context.Context, in *DeleteDataServerRequest, opts ...grpc.CallOption) (*DeleteDataServerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDataServerResponse)
	err := c.cc.Invoke(ctx, OxiaAdmin_DeleteDataServer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oxiaAdminClient) CreateNamespace(ctx context.Context, in *CreateNamespaceRequest, opts ...grpc.CallOption) (*CreateNamespaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNamespaceResponse)
	err := c.cc.Invoke(ctx, OxiaAdmin_CreateNamespace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oxiaAdminClient) PatchNamespace(ctx context.Context, in *PatchNamespaceRequest, opts ...grpc.CallOption) (*PatchNamespaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PatchNamespaceResponse)
	err := c.cc.Invoke(ctx, OxiaAdmin_PatchNamespace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oxiaAdminClient) DeleteNamespace(ctx context.Context, in *DeleteNamespaceRequest, opts ...grpc.CallOption) (*DeleteNamespaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteNamespaceResponse)
	err := c.cc.Invoke(ctx, OxiaAdmin_DeleteNamespace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oxiaAdminClient) GetNamespace(ctx context.Context, in *GetNamespaceRequest, opts ...grpc.CallOption) (*GetNamespaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNamespaceResponse)
	err := c.cc.Invoke(ctx, OxiaAdmin_GetNamespace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oxiaAdminClient) ListNamespaces(ctx context.Context, in *ListNamespacesRequest, opts ...grpc.CallOption) (*ListNamespacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNamespacesResponse)
	err := c.cc.Invoke(ctx, OxiaAdmin_ListNamespaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oxiaAdminClient) GetClusterPolicy(ctx context.Context, in *GetClusterPolicyRequest, opts ...grpc.CallOption) (*GetClusterPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClusterPolicyResponse)
	err := c.cc.Invoke(ctx, OxiaAdmin_GetClusterPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oxiaAdminClient) PatchClusterPolicy(ctx context.Context, in *PatchClusterPolicyRequest, opts ...grpc.CallOption) (*PatchClusterPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PatchClusterPolicyResponse)
	err := c.cc.Invoke(ctx, OxiaAdmin_PatchClusterPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oxiaAdminClient) SplitShard(ctx context.Context, in *SplitShardRequest, opts ...grpc.CallOption) (*SplitShardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SplitShardResponse)
	err := c.cc.Invoke(ctx, OxiaAdmin_SplitShard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OxiaAdminServer is the server API for OxiaAdmin service.
// All implementations must embed UnimplementedOxiaAdminServer
// for forward compatibility.
type OxiaAdminServer interface {
	ListDataServers(context.Context, *ListDataServersRequest) (*ListDataServersResponse, error)
	GetDataServer(context.Context, *GetDataServerRequest) (*GetDataServerResponse, error)
	CreateDataServer(context.Context, *CreateDataServerRequest) (*CreateDataServerResponse, error)
	PatchDataServer(context.Context, *PatchDataServerRequest) (*PatchDataServerResponse, error)
	DeleteDataServer(context.Context, *DeleteDataServerRequest) (*DeleteDataServerResponse, error)
	CreateNamespace(context.Context, *CreateNamespaceRequest) (*CreateNamespaceResponse, error)
	PatchNamespace(context.Context, *PatchNamespaceRequest) (*PatchNamespaceResponse, error)
	DeleteNamespace(context.Context, *DeleteNamespaceRequest) (*DeleteNamespaceResponse, error)
	GetNamespace(context.Context, *GetNamespaceRequest) (*GetNamespaceResponse, error)
	ListNamespaces(context.Context, *ListNamespacesRequest) (*ListNamespacesResponse, error)
	GetClusterPolicy(context.Context, *GetClusterPolicyRequest) (*GetClusterPolicyResponse, error)
	PatchClusterPolicy(context.Context, *PatchClusterPolicyRequest) (*PatchClusterPolicyResponse, error)
	// *
	// Triggers a shard split. The specified shard is split into two child
	// shards at the given split point (or midpoint if not specified).
	SplitShard(context.Context, *SplitShardRequest) (*SplitShardResponse, error)
	mustEmbedUnimplementedOxiaAdminServer()
}

// UnimplementedOxiaAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOxiaAdminServer struct{}

func (UnimplementedOxiaAdminServer) ListDataServers(context.Context, *ListDataServersRequest) (*ListDataServersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDataServers not implemented")
}
func (UnimplementedOxiaAdminServer) GetDataServer(context.Context, *GetDataServerRequest) (*GetDataServerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDataServer not implemented")
}
func (UnimplementedOxiaAdminServer) CreateDataServer(context.Context, *CreateDataServerRequest) (*CreateDataServerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDataServer not implemented")
}
func (UnimplementedOxiaAdminServer) PatchDataServer(context.Context, *PatchDataServerRequest) (*PatchDataServerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PatchDataServer not implemented")
}
func (UnimplementedOxiaAdminServer) DeleteDataServer(context.Context, *DeleteDataServerRequest) (*DeleteDataServerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDataServer not implemented")
}
func (UnimplementedOxiaAdminServer) CreateNamespace(context.Context, *CreateNamespaceRequest) (*CreateNamespaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNamespace not implemented")
}
func (UnimplementedOxiaAdminServer) PatchNamespace(context.Context, *PatchNamespaceRequest) (*PatchNamespaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PatchNamespace not implemented")
}
func (UnimplementedOxiaAdminServer) DeleteNamespace(context.Context, *DeleteNamespaceRequest) (*DeleteNamespaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNamespace not implemented")
}
func (UnimplementedOxiaAdminServer) GetNamespace(context.Context, *GetNamespaceRequest) (*GetNamespaceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNamespace not implemented")
}
func (UnimplementedOxiaAdminServer) ListNamespaces(context.Context, *ListNamespacesRequest) (*ListNamespacesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNamespaces not implemented")
}
func (UnimplementedOxiaAdminServer) GetClusterPolicy(context.Context, *GetClusterPolicyRequest) (*GetClusterPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClusterPolicy not implemented")
}
func (UnimplementedOxiaAdminServer) PatchClusterPolicy(context.Context, *PatchClusterPolicyRequest) (*PatchClusterPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PatchClusterPolicy not implemented")
}
func (UnimplementedOxiaAdminServer) SplitShard(context.Context, *SplitShardRequest) (*SplitShardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SplitShard not implemented")
}
func (UnimplementedOxiaAdminServer) mustEmbedUnimplementedOxiaAdminServer() {}
func (UnimplementedOxiaAdminServer) testEmbeddedByValue()                   {}

// UnsafeOxiaAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OxiaAdminServer will
// result in compilation errors.
type UnsafeOxiaAdminServer interface {
	mustEmbedUnimplementedOxiaAdminServer()
}

func RegisterOxiaAdminServer(s grpc.ServiceRegistrar, srv OxiaAdminServer) {
	// If the following call panics, it indicates UnimplementedOxiaAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OxiaAdmin_ServiceDesc, srv)
}

func _OxiaAdmin_ListDataServers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDataServersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OxiaAdminServer).ListDataServers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OxiaAdmin_ListDataServers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OxiaAdminServer).ListDataServers(ctx, req.(*ListDataServersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OxiaAdmin_GetDataServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OxiaAdminServer).GetDataServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OxiaAdmin_GetDataServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OxiaAdminServer).GetDataServer(ctx, req.(*GetDataServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OxiaAdmin_CreateDataServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDataServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OxiaAdminServer).CreateDataServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OxiaAdmin_CreateDataServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OxiaAdminServer).CreateDataServer(ctx, req.(*CreateDataServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OxiaAdmin_PatchDataServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchDataServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OxiaAdminServer).PatchDataServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OxiaAdmin_PatchDataServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OxiaAdminServer).PatchDataServer(ctx, req.(*PatchDataServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OxiaAdmin_DeleteDataServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDataServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OxiaAdminServer).DeleteDataServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OxiaAdmin_DeleteDataServer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OxiaAdminServer).DeleteDataServer(ctx, req.(*DeleteDataServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OxiaAdmin_CreateNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OxiaAdminServer).CreateNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OxiaAdmin_CreateNamespace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OxiaAdminServer).CreateNamespace(ctx, req.(*CreateNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OxiaAdmin_PatchNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OxiaAdminServer).PatchNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OxiaAdmin_PatchNamespace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OxiaAdminServer).PatchNamespace(ctx, req.(*PatchNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OxiaAdmin_DeleteNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OxiaAdminServer).DeleteNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OxiaAdmin_DeleteNamespace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OxiaAdminServer).DeleteNamespace(ctx, req.(*DeleteNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OxiaAdmin_GetNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OxiaAdminServer).GetNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OxiaAdmin_GetNamespace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OxiaAdminServer).GetNamespace(ctx, req.(*GetNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OxiaAdmin_ListNamespaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNamespacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OxiaAdminServer).ListNamespaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OxiaAdmin_ListNamespaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OxiaAdminServer).ListNamespaces(ctx, req.(*ListNamespacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OxiaAdmin_GetClusterPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OxiaAdminServer).GetClusterPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OxiaAdmin_GetClusterPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OxiaAdminServer).GetClusterPolicy(ctx, req.(*GetClusterPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OxiaAdmin_PatchClusterPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchClusterPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OxiaAdminServer).PatchClusterPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OxiaAdmin_PatchClusterPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OxiaAdminServer).PatchClusterPolicy(ctx, req.(*PatchClusterPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OxiaAdmin_SplitShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SplitShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OxiaAdminServer).SplitShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OxiaAdmin_SplitShard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OxiaAdminServer).SplitShard(ctx, req.(*SplitShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OxiaAdmin_ServiceDesc is the grpc.ServiceDesc for OxiaAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OxiaAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "io.oxia.proto.v1.OxiaAdmin",
	HandlerType: (*OxiaAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDataServers",
			Handler:    _OxiaAdmin_ListDataServers_Handler,
		},
		{
			MethodName: "GetDataServer",
			Handler:    _OxiaAdmin_GetDataServer_Handler,
		},
		{
			MethodName: "CreateDataServer",
			Handler:    _OxiaAdmin_CreateDataServer_Handler,
		},
		{
			MethodName: "PatchDataServer",
			Handler:    _OxiaAdmin_PatchDataServer_Handler,
		},
		{
			MethodName: "DeleteDataServer",
			Handler:    _OxiaAdmin_DeleteDataServer_Handler,
		},
		{
			MethodName: "CreateNamespace",
			Handler:    _OxiaAdmin_CreateNamespace_Handler,
		},
		{
			MethodName: "PatchNamespace",
			Handler:    _OxiaAdmin_PatchNamespace_Handler,
		},
		{
			MethodName: "DeleteNamespace",
			Handler:    _OxiaAdmin_DeleteNamespace_Handler,
		},
		{
			MethodName: "GetNamespace",
			Handler:    _OxiaAdmin_GetNamespace_Handler,
		},
		{
			MethodName: "ListNamespaces",
			Handler:    _OxiaAdmin_ListNamespaces_Handler,
		},
		{
			MethodName: "GetClusterPolicy",
			Handler:    _OxiaAdmin_GetClusterPolicy_Handler,
		},
		{
			MethodName: "PatchClusterPolicy",
			Handler:    _OxiaAdmin_PatchClusterPolicy_Handler,
		},
		{
			MethodName: "SplitShard",
			Handler:    _OxiaAdmin_SplitShard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin.proto",
}
