// Copyright 2023-2025 The Oxia Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: metadata.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataServerIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Public        string                 `protobuf:"bytes,2,opt,name=public,proto3" json:"public,omitempty"`
	Internal      string                 `protobuf:"bytes,3,opt,name=internal,proto3" json:"internal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataServerIdentity) Reset() {
	*x = DataServerIdentity{}
	mi := &file_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataServerIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataServerIdentity) ProtoMessage() {}

func (x *DataServerIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataServerIdentity.ProtoReflect.Descriptor instead.
func (*DataServerIdentity) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *DataServerIdentity) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *DataServerIdentity) GetPublic() string {
	if x != nil {
		return x.Public
	}
	return ""
}

func (x *DataServerIdentity) GetInternal() string {
	if x != nil {
		return x.Internal
	}
	return ""
}

type DataServerMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        map[string]string      `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataServerMetadata) Reset() {
	*x = DataServerMetadata{}
	mi := &file_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataServerMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataServerMetadata) ProtoMessage() {}

func (x *DataServerMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataServerMetadata.ProtoReflect.Descriptor instead.
func (*DataServerMetadata) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *DataServerMetadata) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type DataServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      *DataServerIdentity    `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Metadata      *DataServerMetadata    `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataServer) Reset() {
	*x = DataServer{}
	mi := &file_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataServer) ProtoMessage() {}

func (x *DataServer) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataServer.ProtoReflect.Descriptor instead.
func (*DataServer) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *DataServer) GetIdentity() *DataServerIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *DataServer) GetMetadata() *DataServerMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type AntiAffinity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        []string               `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AntiAffinity) Reset() {
	*x = AntiAffinity{}
	mi := &file_metadata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntiAffinity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntiAffinity) ProtoMessage() {}

func (x *AntiAffinity) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntiAffinity.ProtoReflect.Descriptor instead.
func (*AntiAffinity) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{3}
}

func (x *AntiAffinity) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *AntiAffinity) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type HierarchyPolicies struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AntiAffinities []*AntiAffinity        `protobuf:"bytes,1,rep,name=antiAffinities,proto3" json:"antiAffinities,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HierarchyPolicies) Reset() {
	*x = HierarchyPolicies{}
	mi := &file_metadata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HierarchyPolicies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HierarchyPolicies) ProtoMessage() {}

func (x *HierarchyPolicies) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HierarchyPolicies.ProtoReflect.Descriptor instead.
func (*HierarchyPolicies) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{4}
}

func (x *HierarchyPolicies) GetAntiAffinities() []*AntiAffinity {
	if x != nil {
		return x.AntiAffinities
	}
	return nil
}

type Namespace struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	InitialShardCount    uint32                 `protobuf:"varint,2,opt,name=initialShardCount,proto3" json:"initialShardCount,omitempty"`
	ReplicationFactor    uint32                 `protobuf:"varint,3,opt,name=replicationFactor,proto3" json:"replicationFactor,omitempty"`
	NotificationsEnabled *bool                  `protobuf:"varint,4,opt,name=notificationsEnabled,proto3,oneof" json:"notificationsEnabled,omitempty"`
	KeySorting           string                 `protobuf:"bytes,5,opt,name=keySorting,proto3" json:"keySorting,omitempty"`
	Policy               *HierarchyPolicies     `protobuf:"bytes,6,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Namespace) Reset() {
	*x = Namespace{}
	mi := &file_metadata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Namespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namespace) ProtoMessage() {}

func (x *Namespace) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namespace.ProtoReflect.Descriptor instead.
func (*Namespace) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{5}
}

func (x *Namespace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Namespace) GetInitialShardCount() uint32 {
	if x != nil {
		return x.InitialShardCount
	}
	return 0
}

func (x *Namespace) GetReplicationFactor() uint32 {
	if x != nil {
		return x.ReplicationFactor
	}
	return 0
}

func (x *Namespace) GetNotificationsEnabled() bool {
	if x != nil && x.NotificationsEnabled != nil {
		return *x.NotificationsEnabled
	}
	return false
}

func (x *Namespace) GetKeySorting() string {
	if x != nil {
		return x.KeySorting
	}
	return ""
}

func (x *Namespace) GetPolicy() *HierarchyPolicies {
	if x != nil {
		return x.Policy
	}
	return nil
}

type LoadBalancer struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ScheduleInterval string                 `protobuf:"bytes,1,opt,name=scheduleInterval,proto3" json:"scheduleInterval,omitempty"`
	QuarantineTime   string                 `protobuf:"bytes,2,opt,name=quarantineTime,proto3" json:"quarantineTime,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LoadBalancer) Reset() {
	*x = LoadBalancer{}
	mi := &file_metadata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadBalancer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadBalancer) ProtoMessage() {}

func (x *LoadBalancer) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadBalancer.ProtoReflect.Descriptor instead.
func (*LoadBalancer) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{6}
}

func (x *LoadBalancer) GetScheduleInterval() string {
	if x != nil {
		return x.ScheduleInterval
	}
	return ""
}

func (x *LoadBalancer) GetQuarantineTime() string {
	if x != nil {
		return x.QuarantineTime
	}
	return ""
}

type ClusterConfiguration struct {
	state                 protoimpl.MessageState         `protogen:"open.v1"`
	Namespaces            []*Namespace                   `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	Servers               []*DataServerIdentity          `protobuf:"bytes,2,rep,name=servers,proto3" json:"servers,omitempty"`
	AllowExtraAuthorities []string                       `protobuf:"bytes,3,rep,name=allowExtraAuthorities,proto3" json:"allowExtraAuthorities,omitempty"`
	ServerMetadata        map[string]*DataServerMetadata `protobuf:"bytes,4,rep,name=serverMetadata,proto3" json:"serverMetadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LoadBalancer          *LoadBalancer                  `protobuf:"bytes,5,opt,name=loadBalancer,proto3" json:"loadBalancer,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ClusterConfiguration) Reset() {
	*x = ClusterConfiguration{}
	mi := &file_metadata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterConfiguration) ProtoMessage() {}

func (x *ClusterConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterConfiguration.ProtoReflect.Descriptor instead.
func (*ClusterConfiguration) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{7}
}

func (x *ClusterConfiguration) GetNamespaces() []*Namespace {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *ClusterConfiguration) GetServers() []*DataServerIdentity {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *ClusterConfiguration) GetAllowExtraAuthorities() []string {
	if x != nil {
		return x.AllowExtraAuthorities
	}
	return nil
}

func (x *ClusterConfiguration) GetServerMetadata() map[string]*DataServerMetadata {
	if x != nil {
		return x.ServerMetadata
	}
	return nil
}

func (x *ClusterConfiguration) GetLoadBalancer() *LoadBalancer {
	if x != nil {
		return x.LoadBalancer
	}
	return nil
}

type HashRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           uint32                 `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max           uint32                 `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashRange) Reset() {
	*x = HashRange{}
	mi := &file_metadata_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashRange) ProtoMessage() {}

func (x *HashRange) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashRange.ProtoReflect.Descriptor instead.
func (*HashRange) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{8}
}

func (x *HashRange) GetMin() uint32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *HashRange) GetMax() uint32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type SplitMetadata struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Phase                   string                 `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	ParentShardId           int64                  `protobuf:"varint,2,opt,name=parentShardId,proto3" json:"parentShardId,omitempty"`
	ChildShardIds           []int64                `protobuf:"varint,3,rep,packed,name=childShardIds,proto3" json:"childShardIds,omitempty"`
	SplitPoint              uint32                 `protobuf:"varint,4,opt,name=splitPoint,proto3" json:"splitPoint,omitempty"`
	SnapshotOffset          int64                  `protobuf:"varint,5,opt,name=snapshotOffset,proto3" json:"snapshotOffset,omitempty"`
	ParentTermAtBootstrap   int64                  `protobuf:"varint,6,opt,name=parentTermAtBootstrap,proto3" json:"parentTermAtBootstrap,omitempty"`
	ChildLeadersAtBootstrap map[int64]string       `protobuf:"bytes,7,rep,name=childLeadersAtBootstrap,proto3" json:"childLeadersAtBootstrap,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SplitMetadata) Reset() {
	*x = SplitMetadata{}
	mi := &file_metadata_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SplitMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SplitMetadata) ProtoMessage() {}

func (x *SplitMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SplitMetadata.ProtoReflect.Descriptor instead.
func (*SplitMetadata) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{9}
}

func (x *SplitMetadata) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *SplitMetadata) GetParentShardId() int64 {
	if x != nil {
		return x.ParentShardId
	}
	return 0
}

func (x *SplitMetadata) GetChildShardIds() []int64 {
	if x != nil {
		return x.ChildShardIds
	}
	return nil
}

func (x *SplitMetadata) GetSplitPoint() uint32 {
	if x != nil {
		return x.SplitPoint
	}
	return 0
}

func (x *SplitMetadata) GetSnapshotOffset() int64 {
	if x != nil {
		return x.SnapshotOffset
	}
	return 0
}

func (x *SplitMetadata) GetParentTermAtBootstrap() int64 {
	if x != nil {
		return x.ParentTermAtBootstrap
	}
	return 0
}

func (x *SplitMetadata) GetChildLeadersAtBootstrap() map[int64]string {
	if x != nil {
		return x.ChildLeadersAtBootstrap
	}
	return nil
}

type ShardMetadata struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Status                  string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Term                    int64                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Leader                  *DataServerIdentity    `protobuf:"bytes,3,opt,name=leader,proto3" json:"leader,omitempty"`
	Ensemble                []*DataServerIdentity  `protobuf:"bytes,4,rep,name=ensemble,proto3" json:"ensemble,omitempty"`
	RemovedNodes            []*DataServerIdentity  `protobuf:"bytes,5,rep,name=removedNodes,proto3" json:"removedNodes,omitempty"`
	PendingDeleteShardNodes []*DataServerIdentity  `protobuf:"bytes,6,rep,name=pendingDeleteShardNodes,proto3" json:"pendingDeleteShardNodes,omitempty"`
	Int32HashRange          *HashRange             `protobuf:"bytes,7,opt,name=int32HashRange,proto3" json:"int32HashRange,omitempty"`
	Split                   *SplitMetadata         `protobuf:"bytes,8,opt,name=split,proto3" json:"split,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ShardMetadata) Reset() {
	*x = ShardMetadata{}
	mi := &file_metadata_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardMetadata) ProtoMessage() {}

func (x *ShardMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardMetadata.ProtoReflect.Descriptor instead.
func (*ShardMetadata) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{10}
}

func (x *ShardMetadata) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ShardMetadata) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *ShardMetadata) GetLeader() *DataServerIdentity {
	if x != nil {
		return x.Leader
	}
	return nil
}

func (x *ShardMetadata) GetEnsemble() []*DataServerIdentity {
	if x != nil {
		return x.Ensemble
	}
	return nil
}

func (x *ShardMetadata) GetRemovedNodes() []*DataServerIdentity {
	if x != nil {
		return x.RemovedNodes
	}
	return nil
}

func (x *ShardMetadata) GetPendingDeleteShardNodes() []*DataServerIdentity {
	if x != nil {
		return x.PendingDeleteShardNodes
	}
	return nil
}

func (x *ShardMetadata) GetInt32HashRange() *HashRange {
	if x != nil {
		return x.Int32HashRange
	}
	return nil
}

func (x *ShardMetadata) GetSplit() *SplitMetadata {
	if x != nil {
		return x.Split
	}
	return nil
}

type NamespaceStatus struct {
	state             protoimpl.MessageState   `protogen:"open.v1"`
	ReplicationFactor uint32                   `protobuf:"varint,1,opt,name=replicationFactor,proto3" json:"replicationFactor,omitempty"`
	Shards            map[int64]*ShardMetadata `protobuf:"bytes,2,rep,name=shards,proto3" json:"shards,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NamespaceStatus) Reset() {
	*x = NamespaceStatus{}
	mi := &file_metadata_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceStatus) ProtoMessage() {}

func (x *NamespaceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceStatus.ProtoReflect.Descriptor instead.
func (*NamespaceStatus) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{11}
}

func (x *NamespaceStatus) GetReplicationFactor() uint32 {
	if x != nil {
		return x.ReplicationFactor
	}
	return 0
}

func (x *NamespaceStatus) GetShards() map[int64]*ShardMetadata {
	if x != nil {
		return x.Shards
	}
	return nil
}

type ClusterStatus struct {
	state            protoimpl.MessageState      `protogen:"open.v1"`
	Namespaces       map[string]*NamespaceStatus `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ShardIdGenerator int64                       `protobuf:"varint,2,opt,name=shardIdGenerator,proto3" json:"shardIdGenerator,omitempty"`
	ServerIdx        uint32                      `protobuf:"varint,3,opt,name=serverIdx,proto3" json:"serverIdx,omitempty"`
	InstanceId       string                      `protobuf:"bytes,4,opt,name=instanceId,proto3" json:"instanceId,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClusterStatus) Reset() {
	*x = ClusterStatus{}
	mi := &file_metadata_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterStatus) ProtoMessage() {}

func (x *ClusterStatus) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterStatus.ProtoReflect.Descriptor instead.
func (*ClusterStatus) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{12}
}

func (x *ClusterStatus) GetNamespaces() map[string]*NamespaceStatus {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *ClusterStatus) GetShardIdGenerator() int64 {
	if x != nil {
		return x.ShardIdGenerator
	}
	return 0
}

func (x *ClusterStatus) GetServerIdx() uint32 {
	if x != nil {
		return x.ServerIdx
	}
	return 0
}

func (x *ClusterStatus) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

var File_metadata_proto protoreflect.FileDescriptor

const file_metadata_proto_rawDesc = "" +
	"\n" +
	"\x0emetadata.proto\x12\x10io.oxia.proto.v1\"j\n" +
	"\x12DataServerIdentity\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x16\n" +
	"\x06public\x18\x02 \x01(\tR\x06public\x12\x1a\n" +
	"\binternal\x18\x03 \x01(\tR\binternalB\a\n" +
	"\x05_name\"\x99\x01\n" +
	"\x12DataServerMetadata\x12H\n" +
	"\x06labels\x18\x01 \x03(\v20.io.oxia.proto.v1.DataServerMetadata.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x01\n" +
	"\n" +
	"DataServer\x12@\n" +
	"\bidentity\x18\x01 \x01(\v2$.io.oxia.proto.v1.DataServerIdentityR\bidentity\x12@\n" +
	"\bmetadata\x18\x02 \x01(\v2$.io.oxia.proto.v1.DataServerMetadataR\bmetadata\":\n" +
	"\fAntiAffinity\x12\x16\n" +
	"\x06labels\x18\x01 \x03(\tR\x06labels\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\"[\n" +
	"\x11HierarchyPolicies\x12F\n" +
	"\x0eantiAffinities\x18\x01 \x03(\v2\x1e.io.oxia.proto.v1.AntiAffinityR\x0eantiAffinities\"\xaa\x02\n" +
	"\tNamespace\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\x11initialShardCount\x18\x02 \x01(\rR\x11initialShardCount\x12,\n" +
	"\x11replicationFactor\x18\x03 \x01(\rR\x11replicationFactor\x127\n" +
	"\x14notificationsEnabled\x18\x04 \x01(\bH\x00R\x14notificationsEnabled\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"keySorting\x18\x05 \x01(\tR\n" +
	"keySorting\x12;\n" +
	"\x06policy\x18\x06 \x01(\v2#.io.oxia.proto.v1.HierarchyPoliciesR\x06policyB\x17\n" +
	"\x15_notificationsEnabled\"b\n" +
	"\fLoadBalancer\x12*\n" +
	"\x10scheduleInterval\x18\x01 \x01(\tR\x10scheduleInterval\x12&\n" +
	"\x0equarantineTime\x18\x02 \x01(\tR\x0equarantineTime\"\xda\x03\n" +
	"\x14ClusterConfiguration\x12;\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\v2\x1b.io.oxia.proto.v1.NamespaceR\n" +
	"namespaces\x12>\n" +
	"\aservers\x18\x02 \x03(\v2$.io.oxia.proto.v1.DataServerIdentityR\aservers\x124\n" +
	"\x15allowExtraAuthorities\x18\x03 \x03(\tR\x15allowExtraAuthorities\x12b\n" +
	"\x0eserverMetadata\x18\x04 \x03(\v2:.io.oxia.proto.v1.ClusterConfiguration.ServerMetadataEntryR\x0eserverMetadata\x12B\n" +
	"\floadBalancer\x18\x05 \x01(\v2\x1e.io.oxia.proto.v1.LoadBalancerR\floadBalancer\x1ag\n" +
	"\x13ServerMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x02 \x01(\v2$.io.oxia.proto.v1.DataServerMetadataR\x05value:\x028\x01\"/\n" +
	"\tHashRange\x12\x10\n" +
	"\x03min\x18\x01 \x01(\rR\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\rR\x03max\"\xb3\x03\n" +
	"\rSplitMetadata\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\x12$\n" +
	"\rparentShardId\x18\x02 \x01(\x03R\rparentShardId\x12$\n" +
	"\rchildShardIds\x18\x03 \x03(\x03R\rchildShardIds\x12\x1e\n" +
	"\n" +
	"splitPoint\x18\x04 \x01(\rR\n" +
	"splitPoint\x12&\n" +
	"\x0esnapshotOffset\x18\x05 \x01(\x03R\x0esnapshotOffset\x124\n" +
	"\x15parentTermAtBootstrap\x18\x06 \x01(\x03R\x15parentTermAtBootstrap\x12v\n" +
	"\x17childLeadersAtBootstrap\x18\a \x03(\v2<.io.oxia.proto.v1.SplitMetadata.ChildLeadersAtBootstrapEntryR\x17childLeadersAtBootstrap\x1aJ\n" +
	"\x1cChildLeadersAtBootstrapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe1\x03\n" +
	"\rShardMetadata\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x03R\x04term\x12<\n" +
	"\x06leader\x18\x03 \x01(\v2$.io.oxia.proto.v1.DataServerIdentityR\x06leader\x12@\n" +
	"\bensemble\x18\x04 \x03(\v2$.io.oxia.proto.v1.DataServerIdentityR\bensemble\x12H\n" +
	"\fremovedNodes\x18\x05 \x03(\v2$.io.oxia.proto.v1.DataServerIdentityR\fremovedNodes\x12^\n" +
	"\x17pendingDeleteShardNodes\x18\x06 \x03(\v2$.io.oxia.proto.v1.DataServerIdentityR\x17pendingDeleteShardNodes\x12C\n" +
	"\x0eint32HashRange\x18\a \x01(\v2\x1b.io.oxia.proto.v1.HashRangeR\x0eint32HashRange\x125\n" +
	"\x05split\x18\b \x01(\v2\x1f.io.oxia.proto.v1.SplitMetadataR\x05split\"\xe2\x01\n" +
	"\x0fNamespaceStatus\x12,\n" +
	"\x11replicationFactor\x18\x01 \x01(\rR\x11replicationFactor\x12E\n" +
	"\x06shards\x18\x02 \x03(\v2-.io.oxia.proto.v1.NamespaceStatus.ShardsEntryR\x06shards\x1aZ\n" +
	"\vShardsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.io.oxia.proto.v1.ShardMetadataR\x05value:\x028\x01\"\xac\x02\n" +
	"\rClusterStatus\x12O\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\v2/.io.oxia.proto.v1.ClusterStatus.NamespacesEntryR\n" +
	"namespaces\x12*\n" +
	"\x10shardIdGenerator\x18\x02 \x01(\x03R\x10shardIdGenerator\x12\x1c\n" +
	"\tserverIdx\x18\x03 \x01(\rR\tserverIdx\x12\x1e\n" +
	"\n" +
	"instanceId\x18\x04 \x01(\tR\n" +
	"instanceId\x1a`\n" +
	"\x0fNamespacesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x127\n" +
	"\x05value\x18\x02 \x01(\v2!.io.oxia.proto.v1.NamespaceStatusR\x05value:\x028\x01B&Z$github.com/oxia-db/oxia/common/protob\x06proto3"

var (
	file_metadata_proto_rawDescOnce sync.Once
	file_metadata_proto_rawDescData []byte
)

func file_metadata_proto_rawDescGZIP() []byte {
	file_metadata_proto_rawDescOnce.Do(func() {
		file_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metadata_proto_rawDesc), len(file_metadata_proto_rawDesc)))
	})
	return file_metadata_proto_rawDescData
}

var file_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_metadata_proto_goTypes = []any{
	(*DataServerIdentity)(nil),   // 0: io.oxia.proto.v1.DataServerIdentity
	(*DataServerMetadata)(nil),   // 1: io.oxia.proto.v1.DataServerMetadata
	(*DataServer)(nil),           // 2: io.oxia.proto.v1.DataServer
	(*AntiAffinity)(nil),         // 3: io.oxia.proto.v1.AntiAffinity
	(*HierarchyPolicies)(nil),    // 4: io.oxia.proto.v1.HierarchyPolicies
	(*Namespace)(nil),            // 5: io.oxia.proto.v1.Namespace
	(*LoadBalancer)(nil),         // 6: io.oxia.proto.v1.LoadBalancer
	(*ClusterConfiguration)(nil), // 7: io.oxia.proto.v1.ClusterConfiguration
	(*HashRange)(nil),            // 8: io.oxia.proto.v1.HashRange
	(*SplitMetadata)(nil),        // 9: io.oxia.proto.v1.SplitMetadata
	(*ShardMetadata)(nil),        // 10: io.oxia.proto.v1.ShardMetadata
	(*NamespaceStatus)(nil),      // 11: io.oxia.proto.v1.NamespaceStatus
	(*ClusterStatus)(nil),        // 12: io.oxia.proto.v1.ClusterStatus
	nil,                          // 13: io.oxia.proto.v1.DataServerMetadata.LabelsEntry
	nil,                          // 14: io.oxia.proto.v1.ClusterConfiguration.ServerMetadataEntry
	nil,                          // 15: io.oxia.proto.v1.SplitMetadata.ChildLeadersAtBootstrapEntry
	nil,                          // 16: io.oxia.proto.v1.NamespaceStatus.ShardsEntry
	nil,                          // 17: io.oxia.proto.v1.ClusterStatus.NamespacesEntry
}
var file_metadata_proto_depIdxs = []int32{
	13, // 0: io.oxia.proto.v1.DataServerMetadata.labels:type_name -> io.oxia.proto.v1.DataServerMetadata.LabelsEntry
	0,  // 1: io.oxia.proto.v1.DataServer.identity:type_name -> io.oxia.proto.v1.DataServerIdentity
	1,  // 2: io.oxia.proto.v1.DataServer.metadata:type_name -> io.oxia.proto.v1.DataServerMetadata
	3,  // 3: io.oxia.proto.v1.HierarchyPolicies.antiAffinities:type_name -> io.oxia.proto.v1.AntiAffinity
	4,  // 4: io.oxia.proto.v1.Namespace.policy:type_name -> io.oxia.proto.v1.HierarchyPolicies
	5,  // 5: io.oxia.proto.v1.ClusterConfiguration.namespaces:type_name -> io.oxia.proto.v1.Namespace
	0,  // 6: io.oxia.proto.v1.ClusterConfiguration.servers:type_name -> io.oxia.proto.v1.DataServerIdentity
	14, // 7: io.oxia.proto.v1.ClusterConfiguration.serverMetadata:type_name -> io.oxia.proto.v1.ClusterConfiguration.ServerMetadataEntry
	6,  // 8: io.oxia.proto.v1.ClusterConfiguration.loadBalancer:type_name -> io.oxia.proto.v1.LoadBalancer
	15, // 9: io.oxia.proto.v1.SplitMetadata.childLeadersAtBootstrap:type_name -> io.oxia.proto.v1.SplitMetadata.ChildLeadersAtBootstrapEntry
	0,  // 10: io.oxia.proto.v1.ShardMetadata.leader:type_name -> io.oxia.proto.v1.DataServerIdentity
	0,  // 11: io.oxia.proto.v1.ShardMetadata.ensemble:type_name -> io.oxia.proto.v1.DataServerIdentity
	0,  // 12: io.oxia.proto.v1.ShardMetadata.removedNodes:type_name -> io.oxia.proto.v1.DataServerIdentity
	0,  // 13: io.oxia.proto.v1.ShardMetadata.pendingDeleteShardNodes:type_name -> io.oxia.proto.v1.DataServerIdentity
	8,  // 14: io.oxia.proto.v1.ShardMetadata.int32HashRange:type_name -> io.oxia.proto.v1.HashRange
	9,  // 15: io.oxia.proto.v1.ShardMetadata.split:type_name -> io.oxia.proto.v1.SplitMetadata
	16, // 16: io.oxia.proto.v1.NamespaceStatus.shards:type_name -> io.oxia.proto.v1.NamespaceStatus.ShardsEntry
	17, // 17: io.oxia.proto.v1.ClusterStatus.namespaces:type_name -> io.oxia.proto.v1.ClusterStatus.NamespacesEntry
	1,  // 18: io.oxia.proto.v1.ClusterConfiguration.ServerMetadataEntry.value:type_name -> io.oxia.proto.v1.DataServerMetadata
	10, // 19: io.oxia.proto.v1.NamespaceStatus.ShardsEntry.value:type_name -> io.oxia.proto.v1.ShardMetadata
	11, // 20: io.oxia.proto.v1.ClusterStatus.NamespacesEntry.value:type_name -> io.oxia.proto.v1.NamespaceStatus
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_metadata_proto_init() }
func file_metadata_proto_init() {
	if File_metadata_proto != nil {
		return
	}
	file_metadata_proto_msgTypes[0].OneofWrappers = []any{}
	file_metadata_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metadata_proto_rawDesc), len(file_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metadata_proto_goTypes,
		DependencyIndexes: file_metadata_proto_depIdxs,
		MessageInfos:      file_metadata_proto_msgTypes,
	}.Build()
	File_metadata_proto = out.File
	file_metadata_proto_goTypes = nil
	file_metadata_proto_depIdxs = nil
}
