// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: metadata.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AntiAffinityMode int32

const (
	AntiAffinityMode_ANTI_AFFINITY_MODE_STRICT AntiAffinityMode = 0
	AntiAffinityMode_ANTI_AFFINITY_MODE_RELAX  AntiAffinityMode = 1
)

// Enum value maps for AntiAffinityMode.
var (
	AntiAffinityMode_name = map[int32]string{
		0: "ANTI_AFFINITY_MODE_STRICT",
		1: "ANTI_AFFINITY_MODE_RELAX",
	}
	AntiAffinityMode_value = map[string]int32{
		"ANTI_AFFINITY_MODE_STRICT": 0,
		"ANTI_AFFINITY_MODE_RELAX":  1,
	}
)

func (x AntiAffinityMode) Enum() *AntiAffinityMode {
	p := new(AntiAffinityMode)
	*p = x
	return p
}

func (x AntiAffinityMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AntiAffinityMode) Descriptor() protoreflect.EnumDescriptor {
	return file_metadata_proto_enumTypes[0].Descriptor()
}

func (AntiAffinityMode) Type() protoreflect.EnumType {
	return &file_metadata_proto_enumTypes[0]
}

func (x AntiAffinityMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AntiAffinityMode.Descriptor instead.
func (AntiAffinityMode) EnumDescriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{0}
}

type KeySorting int32

const (
	KeySorting_KEY_SORTING_NATURE       KeySorting = 0
	KeySorting_KEY_SORTING_HIERARCHICAL KeySorting = 1
)

// Enum value maps for KeySorting.
var (
	KeySorting_name = map[int32]string{
		0: "KEY_SORTING_NATURE",
		1: "KEY_SORTING_HIERARCHICAL",
	}
	KeySorting_value = map[string]int32{
		"KEY_SORTING_NATURE":       0,
		"KEY_SORTING_HIERARCHICAL": 1,
	}
)

func (x KeySorting) Enum() *KeySorting {
	p := new(KeySorting)
	*p = x
	return p
}

func (x KeySorting) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeySorting) Descriptor() protoreflect.EnumDescriptor {
	return file_metadata_proto_enumTypes[1].Descriptor()
}

func (KeySorting) Type() protoreflect.EnumType {
	return &file_metadata_proto_enumTypes[1]
}

func (x KeySorting) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeySorting.Descriptor instead.
func (KeySorting) EnumDescriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{1}
}

type LeaseState int32

const (
	LeaseState_LEASE_STATE_UNSPECIFIED LeaseState = 0
	LeaseState_LEASE_STATE_HELD        LeaseState = 1
	LeaseState_LEASE_STATE_UNHELD      LeaseState = 2
)

// Enum value maps for LeaseState.
var (
	LeaseState_name = map[int32]string{
		0: "LEASE_STATE_UNSPECIFIED",
		1: "LEASE_STATE_HELD",
		2: "LEASE_STATE_UNHELD",
	}
	LeaseState_value = map[string]int32{
		"LEASE_STATE_UNSPECIFIED": 0,
		"LEASE_STATE_HELD":        1,
		"LEASE_STATE_UNHELD":      2,
	}
)

func (x LeaseState) Enum() *LeaseState {
	p := new(LeaseState)
	*p = x
	return p
}

func (x LeaseState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LeaseState) Descriptor() protoreflect.EnumDescriptor {
	return file_metadata_proto_enumTypes[2].Descriptor()
}

func (LeaseState) Type() protoreflect.EnumType {
	return &file_metadata_proto_enumTypes[2]
}

func (x LeaseState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LeaseState.Descriptor instead.
func (LeaseState) EnumDescriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{2}
}

type ShardStatus int32

const (
	ShardStatus_SHARD_STATUS_UNKNOWN  ShardStatus = 0
	ShardStatus_SHARD_STATUS_STEADY   ShardStatus = 1
	ShardStatus_SHARD_STATUS_ELECTION ShardStatus = 2
	ShardStatus_SHARD_STATUS_DELETING ShardStatus = 3
)

// Enum value maps for ShardStatus.
var (
	ShardStatus_name = map[int32]string{
		0: "SHARD_STATUS_UNKNOWN",
		1: "SHARD_STATUS_STEADY",
		2: "SHARD_STATUS_ELECTION",
		3: "SHARD_STATUS_DELETING",
	}
	ShardStatus_value = map[string]int32{
		"SHARD_STATUS_UNKNOWN":  0,
		"SHARD_STATUS_STEADY":   1,
		"SHARD_STATUS_ELECTION": 2,
		"SHARD_STATUS_DELETING": 3,
	}
)

func (x ShardStatus) Enum() *ShardStatus {
	p := new(ShardStatus)
	*p = x
	return p
}

func (x ShardStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShardStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_metadata_proto_enumTypes[3].Descriptor()
}

func (ShardStatus) Type() protoreflect.EnumType {
	return &file_metadata_proto_enumTypes[3]
}

func (x ShardStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShardStatus.Descriptor instead.
func (ShardStatus) EnumDescriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{3}
}

type SplitPhase int32

const (
	SplitPhase_SPLIT_PHASE_BOOTSTRAP SplitPhase = 0
	SplitPhase_SPLIT_PHASE_CATCH_UP  SplitPhase = 1
	SplitPhase_SPLIT_PHASE_CUTOVER   SplitPhase = 2
)

// Enum value maps for SplitPhase.
var (
	SplitPhase_name = map[int32]string{
		0: "SPLIT_PHASE_BOOTSTRAP",
		1: "SPLIT_PHASE_CATCH_UP",
		2: "SPLIT_PHASE_CUTOVER",
	}
	SplitPhase_value = map[string]int32{
		"SPLIT_PHASE_BOOTSTRAP": 0,
		"SPLIT_PHASE_CATCH_UP":  1,
		"SPLIT_PHASE_CUTOVER":   2,
	}
)

func (x SplitPhase) Enum() *SplitPhase {
	p := new(SplitPhase)
	*p = x
	return p
}

func (x SplitPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SplitPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_metadata_proto_enumTypes[4].Descriptor()
}

func (SplitPhase) Type() protoreflect.EnumType {
	return &file_metadata_proto_enumTypes[4]
}

func (x SplitPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SplitPhase.Descriptor instead.
func (SplitPhase) EnumDescriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{4}
}

type DataServer struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PublicAddress   string                 `protobuf:"bytes,2,opt,name=public_address,json=publicAddress,proto3" json:"public_address,omitempty"`
	InternalAddress string                 `protobuf:"bytes,3,opt,name=internal_address,json=internalAddress,proto3" json:"internal_address,omitempty"`
	Labels          map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DataServer) Reset() {
	*x = DataServer{}
	mi := &file_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataServer) ProtoMessage() {}

func (x *DataServer) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataServer.ProtoReflect.Descriptor instead.
func (*DataServer) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *DataServer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DataServer) GetPublicAddress() string {
	if x != nil {
		return x.PublicAddress
	}
	return ""
}

func (x *DataServer) GetInternalAddress() string {
	if x != nil {
		return x.InternalAddress
	}
	return ""
}

func (x *DataServer) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type AntiAffinity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        []string               `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`
	Mode          AntiAffinityMode       `protobuf:"varint,2,opt,name=mode,proto3,enum=metadata.AntiAffinityMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AntiAffinity) Reset() {
	*x = AntiAffinity{}
	mi := &file_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AntiAffinity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AntiAffinity) ProtoMessage() {}

func (x *AntiAffinity) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AntiAffinity.ProtoReflect.Descriptor instead.
func (*AntiAffinity) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *AntiAffinity) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *AntiAffinity) GetMode() AntiAffinityMode {
	if x != nil {
		return x.Mode
	}
	return AntiAffinityMode_ANTI_AFFINITY_MODE_STRICT
}

type HierarchyPolicies struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AntiAffinities      []*AntiAffinity        `protobuf:"bytes,1,rep,name=anti_affinities,json=antiAffinities,proto3" json:"anti_affinities,omitempty"`
	InitShardCount      *uint32                `protobuf:"varint,2,opt,name=init_shard_count,json=initShardCount,proto3,oneof" json:"init_shard_count,omitempty"`
	ReplicationFactor   *uint32                `protobuf:"varint,3,opt,name=replication_factor,json=replicationFactor,proto3,oneof" json:"replication_factor,omitempty"`
	NotificationEnabled *bool                  `protobuf:"varint,4,opt,name=notification_enabled,json=notificationEnabled,proto3,oneof" json:"notification_enabled,omitempty"`
	KeySort             *string                `protobuf:"bytes,5,opt,name=key_sort,json=keySort,proto3,oneof" json:"key_sort,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HierarchyPolicies) Reset() {
	*x = HierarchyPolicies{}
	mi := &file_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HierarchyPolicies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HierarchyPolicies) ProtoMessage() {}

func (x *HierarchyPolicies) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HierarchyPolicies.ProtoReflect.Descriptor instead.
func (*HierarchyPolicies) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *HierarchyPolicies) GetAntiAffinities() []*AntiAffinity {
	if x != nil {
		return x.AntiAffinities
	}
	return nil
}

func (x *HierarchyPolicies) GetInitShardCount() uint32 {
	if x != nil && x.InitShardCount != nil {
		return *x.InitShardCount
	}
	return 0
}

func (x *HierarchyPolicies) GetReplicationFactor() uint32 {
	if x != nil && x.ReplicationFactor != nil {
		return *x.ReplicationFactor
	}
	return 0
}

func (x *HierarchyPolicies) GetNotificationEnabled() bool {
	if x != nil && x.NotificationEnabled != nil {
		return *x.NotificationEnabled
	}
	return false
}

func (x *HierarchyPolicies) GetKeySort() string {
	if x != nil && x.KeySort != nil {
		return *x.KeySort
	}
	return ""
}

type LoadBalancerPolicies struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ScheduleInterval *durationpb.Duration   `protobuf:"bytes,1,opt,name=schedule_interval,json=scheduleInterval,proto3" json:"schedule_interval,omitempty"`
	QuarantineTime   *durationpb.Duration   `protobuf:"bytes,2,opt,name=quarantine_time,json=quarantineTime,proto3" json:"quarantine_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LoadBalancerPolicies) Reset() {
	*x = LoadBalancerPolicies{}
	mi := &file_metadata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadBalancerPolicies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadBalancerPolicies) ProtoMessage() {}

func (x *LoadBalancerPolicies) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadBalancerPolicies.ProtoReflect.Descriptor instead.
func (*LoadBalancerPolicies) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{3}
}

func (x *LoadBalancerPolicies) GetScheduleInterval() *durationpb.Duration {
	if x != nil {
		return x.ScheduleInterval
	}
	return nil
}

func (x *LoadBalancerPolicies) GetQuarantineTime() *durationpb.Duration {
	if x != nil {
		return x.QuarantineTime
	}
	return nil
}

type Namespace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Policies      *HierarchyPolicies     `protobuf:"bytes,2,opt,name=policies,proto3,oneof" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Namespace) Reset() {
	*x = Namespace{}
	mi := &file_metadata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Namespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namespace) ProtoMessage() {}

func (x *Namespace) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namespace.ProtoReflect.Descriptor instead.
func (*Namespace) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{4}
}

func (x *Namespace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Namespace) GetPolicies() *HierarchyPolicies {
	if x != nil {
		return x.Policies
	}
	return nil
}

type Cluster struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	DataServers             []*DataServer          `protobuf:"bytes,1,rep,name=data_servers,json=dataServers,proto3" json:"data_servers,omitempty"`
	Namespaces              []*Namespace           `protobuf:"bytes,2,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	Policies                *HierarchyPolicies     `protobuf:"bytes,3,opt,name=policies,proto3,oneof" json:"policies,omitempty"`
	LoadBalancer            *LoadBalancerPolicies  `protobuf:"bytes,4,opt,name=loadBalancer,proto3,oneof" json:"loadBalancer,omitempty"`
	AllowedExtraAuthorities []string               `protobuf:"bytes,5,rep,name=allowed_extra_authorities,json=allowedExtraAuthorities,proto3" json:"allowed_extra_authorities,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Cluster) Reset() {
	*x = Cluster{}
	mi := &file_metadata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cluster) ProtoMessage() {}

func (x *Cluster) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cluster.ProtoReflect.Descriptor instead.
func (*Cluster) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{5}
}

func (x *Cluster) GetDataServers() []*DataServer {
	if x != nil {
		return x.DataServers
	}
	return nil
}

func (x *Cluster) GetNamespaces() []*Namespace {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *Cluster) GetPolicies() *HierarchyPolicies {
	if x != nil {
		return x.Policies
	}
	return nil
}

func (x *Cluster) GetLoadBalancer() *LoadBalancerPolicies {
	if x != nil {
		return x.LoadBalancer
	}
	return nil
}

func (x *Cluster) GetAllowedExtraAuthorities() []string {
	if x != nil {
		return x.AllowedExtraAuthorities
	}
	return nil
}

type Int32HashRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           uint32                 `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max           uint32                 `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Int32HashRange) Reset() {
	*x = Int32HashRange{}
	mi := &file_metadata_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int32HashRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int32HashRange) ProtoMessage() {}

func (x *Int32HashRange) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int32HashRange.ProtoReflect.Descriptor instead.
func (*Int32HashRange) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{6}
}

func (x *Int32HashRange) GetMin() uint32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Int32HashRange) GetMax() uint32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type ShardSplittingState struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Phase                   SplitPhase             `protobuf:"varint,1,opt,name=phase,proto3,enum=metadata.SplitPhase" json:"phase,omitempty"`
	ParentShardId           *int64                 `protobuf:"varint,2,opt,name=parent_shard_id,json=parentShardId,proto3,oneof" json:"parent_shard_id,omitempty"`
	ChildShardIds           []int64                `protobuf:"varint,3,rep,packed,name=child_shard_ids,json=childShardIds,proto3" json:"child_shard_ids,omitempty"`
	SplitPoint              uint32                 `protobuf:"varint,4,opt,name=split_point,json=splitPoint,proto3" json:"split_point,omitempty"`
	SnapshotOffset          *int64                 `protobuf:"varint,5,opt,name=snapshot_offset,json=snapshotOffset,proto3,oneof" json:"snapshot_offset,omitempty"`
	ParentTermAtBootstrap   *int64                 `protobuf:"varint,6,opt,name=parent_term_at_bootstrap,json=parentTermAtBootstrap,proto3,oneof" json:"parent_term_at_bootstrap,omitempty"`
	ChildLeadersAtBootstrap map[int64]string       `protobuf:"bytes,7,rep,name=child_leaders_at_bootstrap,json=childLeadersAtBootstrap,proto3" json:"child_leaders_at_bootstrap,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ShardSplittingState) Reset() {
	*x = ShardSplittingState{}
	mi := &file_metadata_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardSplittingState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardSplittingState) ProtoMessage() {}

func (x *ShardSplittingState) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardSplittingState.ProtoReflect.Descriptor instead.
func (*ShardSplittingState) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{7}
}

func (x *ShardSplittingState) GetPhase() SplitPhase {
	if x != nil {
		return x.Phase
	}
	return SplitPhase_SPLIT_PHASE_BOOTSTRAP
}

func (x *ShardSplittingState) GetParentShardId() int64 {
	if x != nil && x.ParentShardId != nil {
		return *x.ParentShardId
	}
	return 0
}

func (x *ShardSplittingState) GetChildShardIds() []int64 {
	if x != nil {
		return x.ChildShardIds
	}
	return nil
}

func (x *ShardSplittingState) GetSplitPoint() uint32 {
	if x != nil {
		return x.SplitPoint
	}
	return 0
}

func (x *ShardSplittingState) GetSnapshotOffset() int64 {
	if x != nil && x.SnapshotOffset != nil {
		return *x.SnapshotOffset
	}
	return 0
}

func (x *ShardSplittingState) GetParentTermAtBootstrap() int64 {
	if x != nil && x.ParentTermAtBootstrap != nil {
		return *x.ParentTermAtBootstrap
	}
	return 0
}

func (x *ShardSplittingState) GetChildLeadersAtBootstrap() map[int64]string {
	if x != nil {
		return x.ChildLeadersAtBootstrap
	}
	return nil
}

type ShardState struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Status                  ShardStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=metadata.ShardStatus" json:"status,omitempty"`
	Term                    int64                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Leader                  string                 `protobuf:"bytes,3,opt,name=leader,proto3" json:"leader,omitempty"`
	Ensemble                []string               `protobuf:"bytes,4,rep,name=ensemble,proto3" json:"ensemble,omitempty"`
	RemovedNodes            []string               `protobuf:"bytes,5,rep,name=removed_nodes,json=removedNodes,proto3" json:"removed_nodes,omitempty"`
	PendingDeleteShardNodes []string               `protobuf:"bytes,6,rep,name=pending_delete_shard_nodes,json=pendingDeleteShardNodes,proto3" json:"pending_delete_shard_nodes,omitempty"`
	Int32HashRange          *Int32HashRange        `protobuf:"bytes,7,opt,name=int32_hash_range,json=int32HashRange,proto3" json:"int32_hash_range,omitempty"`
	Split                   *ShardSplittingState   `protobuf:"bytes,8,opt,name=split,proto3,oneof" json:"split,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ShardState) Reset() {
	*x = ShardState{}
	mi := &file_metadata_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardState) ProtoMessage() {}

func (x *ShardState) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardState.ProtoReflect.Descriptor instead.
func (*ShardState) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{8}
}

func (x *ShardState) GetStatus() ShardStatus {
	if x != nil {
		return x.Status
	}
	return ShardStatus_SHARD_STATUS_UNKNOWN
}

func (x *ShardState) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *ShardState) GetLeader() string {
	if x != nil {
		return x.Leader
	}
	return ""
}

func (x *ShardState) GetEnsemble() []string {
	if x != nil {
		return x.Ensemble
	}
	return nil
}

func (x *ShardState) GetRemovedNodes() []string {
	if x != nil {
		return x.RemovedNodes
	}
	return nil
}

func (x *ShardState) GetPendingDeleteShardNodes() []string {
	if x != nil {
		return x.PendingDeleteShardNodes
	}
	return nil
}

func (x *ShardState) GetInt32HashRange() *Int32HashRange {
	if x != nil {
		return x.Int32HashRange
	}
	return nil
}

func (x *ShardState) GetSplit() *ShardSplittingState {
	if x != nil {
		return x.Split
	}
	return nil
}

type NamespaceState struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ReplicationFactor uint32                 `protobuf:"varint,1,opt,name=replication_factor,json=replicationFactor,proto3" json:"replication_factor,omitempty"`
	Shards            map[int64]*ShardState  `protobuf:"bytes,2,rep,name=shards,proto3" json:"shards,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NamespaceState) Reset() {
	*x = NamespaceState{}
	mi := &file_metadata_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceState) ProtoMessage() {}

func (x *NamespaceState) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceState.ProtoReflect.Descriptor instead.
func (*NamespaceState) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{9}
}

func (x *NamespaceState) GetReplicationFactor() uint32 {
	if x != nil {
		return x.ReplicationFactor
	}
	return 0
}

func (x *NamespaceState) GetShards() map[int64]*ShardState {
	if x != nil {
		return x.Shards
	}
	return nil
}

type ClusterState struct {
	state            protoimpl.MessageState     `protogen:"open.v1"`
	Namespaces       map[string]*NamespaceState `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ShardIdGenerator int64                      `protobuf:"varint,2,opt,name=shard_id_generator,json=shardIdGenerator,proto3" json:"shard_id_generator,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClusterState) Reset() {
	*x = ClusterState{}
	mi := &file_metadata_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterState) ProtoMessage() {}

func (x *ClusterState) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterState.ProtoReflect.Descriptor instead.
func (*ClusterState) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{10}
}

func (x *ClusterState) GetNamespaces() map[string]*NamespaceState {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *ClusterState) GetShardIdGenerator() int64 {
	if x != nil {
		return x.ShardIdGenerator
	}
	return 0
}

var File_metadata_proto protoreflect.FileDescriptor

const file_metadata_proto_rawDesc = "" +
	"\n" +
	"\x0emetadata.proto\x12\bmetadata\x1a\x1egoogle/protobuf/duration.proto\"\xe7\x01\n" +
	"\n" +
	"DataServer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0epublic_address\x18\x02 \x01(\tR\rpublicAddress\x12)\n" +
	"\x10internal_address\x18\x03 \x01(\tR\x0finternalAddress\x128\n" +
	"\x06labels\x18\x04 \x03(\v2 .metadata.DataServer.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"V\n" +
	"\fAntiAffinity\x12\x16\n" +
	"\x06labels\x18\x01 \x03(\tR\x06labels\x12.\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x1a.metadata.AntiAffinityModeR\x04mode\"\xe1\x02\n" +
	"\x11HierarchyPolicies\x12?\n" +
	"\x0fanti_affinities\x18\x01 \x03(\v2\x16.metadata.AntiAffinityR\x0eantiAffinities\x12-\n" +
	"\x10init_shard_count\x18\x02 \x01(\rH\x00R\x0einitShardCount\x88\x01\x01\x122\n" +
	"\x12replication_factor\x18\x03 \x01(\rH\x01R\x11replicationFactor\x88\x01\x01\x126\n" +
	"\x14notification_enabled\x18\x04 \x01(\bH\x02R\x13notificationEnabled\x88\x01\x01\x12\x1e\n" +
	"\bkey_sort\x18\x05 \x01(\tH\x03R\akeySort\x88\x01\x01B\x13\n" +
	"\x11_init_shard_countB\x15\n" +
	"\x13_replication_factorB\x17\n" +
	"\x15_notification_enabledB\v\n" +
	"\t_key_sort\"\xa2\x01\n" +
	"\x14LoadBalancerPolicies\x12F\n" +
	"\x11schedule_interval\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x10scheduleInterval\x12B\n" +
	"\x0fquarantine_time\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x0equarantineTime\"j\n" +
	"\tNamespace\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12<\n" +
	"\bpolicies\x18\x02 \x01(\v2\x1b.metadata.HierarchyPoliciesH\x00R\bpolicies\x88\x01\x01B\v\n" +
	"\t_policies\"\xd8\x02\n" +
	"\aCluster\x127\n" +
	"\fdata_servers\x18\x01 \x03(\v2\x14.metadata.DataServerR\vdataServers\x123\n" +
	"\n" +
	"namespaces\x18\x02 \x03(\v2\x13.metadata.NamespaceR\n" +
	"namespaces\x12<\n" +
	"\bpolicies\x18\x03 \x01(\v2\x1b.metadata.HierarchyPoliciesH\x00R\bpolicies\x88\x01\x01\x12G\n" +
	"\floadBalancer\x18\x04 \x01(\v2\x1e.metadata.LoadBalancerPoliciesH\x01R\floadBalancer\x88\x01\x01\x12:\n" +
	"\x19allowed_extra_authorities\x18\x05 \x03(\tR\x17allowedExtraAuthoritiesB\v\n" +
	"\t_policiesB\x0f\n" +
	"\r_loadBalancer\"4\n" +
	"\x0eInt32HashRange\x12\x10\n" +
	"\x03min\x18\x01 \x01(\rR\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\rR\x03max\"\xad\x04\n" +
	"\x13ShardSplittingState\x12*\n" +
	"\x05phase\x18\x01 \x01(\x0e2\x14.metadata.SplitPhaseR\x05phase\x12+\n" +
	"\x0fparent_shard_id\x18\x02 \x01(\x03H\x00R\rparentShardId\x88\x01\x01\x12&\n" +
	"\x0fchild_shard_ids\x18\x03 \x03(\x03R\rchildShardIds\x12\x1f\n" +
	"\vsplit_point\x18\x04 \x01(\rR\n" +
	"splitPoint\x12,\n" +
	"\x0fsnapshot_offset\x18\x05 \x01(\x03H\x01R\x0esnapshotOffset\x88\x01\x01\x12<\n" +
	"\x18parent_term_at_bootstrap\x18\x06 \x01(\x03H\x02R\x15parentTermAtBootstrap\x88\x01\x01\x12w\n" +
	"\x1achild_leaders_at_bootstrap\x18\a \x03(\v2:.metadata.ShardSplittingState.ChildLeadersAtBootstrapEntryR\x17childLeadersAtBootstrap\x1aJ\n" +
	"\x1cChildLeadersAtBootstrapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x12\n" +
	"\x10_parent_shard_idB\x12\n" +
	"\x10_snapshot_offsetB\x1b\n" +
	"\x19_parent_term_at_bootstrap\"\xed\x02\n" +
	"\n" +
	"ShardState\x12-\n" +
	"\x06status\x18\x01 \x01(\x0e2\x15.metadata.ShardStatusR\x06status\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x03R\x04term\x12\x16\n" +
	"\x06leader\x18\x03 \x01(\tR\x06leader\x12\x1a\n" +
	"\bensemble\x18\x04 \x03(\tR\bensemble\x12#\n" +
	"\rremoved_nodes\x18\x05 \x03(\tR\fremovedNodes\x12;\n" +
	"\x1apending_delete_shard_nodes\x18\x06 \x03(\tR\x17pendingDeleteShardNodes\x12B\n" +
	"\x10int32_hash_range\x18\a \x01(\v2\x18.metadata.Int32HashRangeR\x0eint32HashRange\x128\n" +
	"\x05split\x18\b \x01(\v2\x1d.metadata.ShardSplittingStateH\x00R\x05split\x88\x01\x01B\b\n" +
	"\x06_split\"\xce\x01\n" +
	"\x0eNamespaceState\x12-\n" +
	"\x12replication_factor\x18\x01 \x01(\rR\x11replicationFactor\x12<\n" +
	"\x06shards\x18\x02 \x03(\v2$.metadata.NamespaceState.ShardsEntryR\x06shards\x1aO\n" +
	"\vShardsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.metadata.ShardStateR\x05value:\x028\x01\"\xdd\x01\n" +
	"\fClusterState\x12F\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\v2&.metadata.ClusterState.NamespacesEntryR\n" +
	"namespaces\x12,\n" +
	"\x12shard_id_generator\x18\x02 \x01(\x03R\x10shardIdGenerator\x1aW\n" +
	"\x0fNamespacesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.metadata.NamespaceStateR\x05value:\x028\x01*O\n" +
	"\x10AntiAffinityMode\x12\x1d\n" +
	"\x19ANTI_AFFINITY_MODE_STRICT\x10\x00\x12\x1c\n" +
	"\x18ANTI_AFFINITY_MODE_RELAX\x10\x01*B\n" +
	"\n" +
	"KeySorting\x12\x16\n" +
	"\x12KEY_SORTING_NATURE\x10\x00\x12\x1c\n" +
	"\x18KEY_SORTING_HIERARCHICAL\x10\x01*W\n" +
	"\n" +
	"LeaseState\x12\x1b\n" +
	"\x17LEASE_STATE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10LEASE_STATE_HELD\x10\x01\x12\x16\n" +
	"\x12LEASE_STATE_UNHELD\x10\x02*v\n" +
	"\vShardStatus\x12\x18\n" +
	"\x14SHARD_STATUS_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13SHARD_STATUS_STEADY\x10\x01\x12\x19\n" +
	"\x15SHARD_STATUS_ELECTION\x10\x02\x12\x19\n" +
	"\x15SHARD_STATUS_DELETING\x10\x03*Z\n" +
	"\n" +
	"SplitPhase\x12\x19\n" +
	"\x15SPLIT_PHASE_BOOTSTRAP\x10\x00\x12\x18\n" +
	"\x14SPLIT_PHASE_CATCH_UP\x10\x01\x12\x17\n" +
	"\x13SPLIT_PHASE_CUTOVER\x10\x02B&Z$github.com/oxia-db/oxia/common/protob\x06proto3"

var (
	file_metadata_proto_rawDescOnce sync.Once
	file_metadata_proto_rawDescData []byte
)

func file_metadata_proto_rawDescGZIP() []byte {
	file_metadata_proto_rawDescOnce.Do(func() {
		file_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metadata_proto_rawDesc), len(file_metadata_proto_rawDesc)))
	})
	return file_metadata_proto_rawDescData
}

var file_metadata_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_metadata_proto_goTypes = []any{
	(AntiAffinityMode)(0),        // 0: metadata.AntiAffinityMode
	(KeySorting)(0),              // 1: metadata.KeySorting
	(LeaseState)(0),              // 2: metadata.LeaseState
	(ShardStatus)(0),             // 3: metadata.ShardStatus
	(SplitPhase)(0),              // 4: metadata.SplitPhase
	(*DataServer)(nil),           // 5: metadata.DataServer
	(*AntiAffinity)(nil),         // 6: metadata.AntiAffinity
	(*HierarchyPolicies)(nil),    // 7: metadata.HierarchyPolicies
	(*LoadBalancerPolicies)(nil), // 8: metadata.LoadBalancerPolicies
	(*Namespace)(nil),            // 9: metadata.Namespace
	(*Cluster)(nil),              // 10: metadata.Cluster
	(*Int32HashRange)(nil),       // 11: metadata.Int32HashRange
	(*ShardSplittingState)(nil),  // 12: metadata.ShardSplittingState
	(*ShardState)(nil),           // 13: metadata.ShardState
	(*NamespaceState)(nil),       // 14: metadata.NamespaceState
	(*ClusterState)(nil),         // 15: metadata.ClusterState
	nil,                          // 16: metadata.DataServer.LabelsEntry
	nil,                          // 17: metadata.ShardSplittingState.ChildLeadersAtBootstrapEntry
	nil,                          // 18: metadata.NamespaceState.ShardsEntry
	nil,                          // 19: metadata.ClusterState.NamespacesEntry
	(*durationpb.Duration)(nil),  // 20: google.protobuf.Duration
}
var file_metadata_proto_depIdxs = []int32{
	16, // 0: metadata.DataServer.labels:type_name -> metadata.DataServer.LabelsEntry
	0,  // 1: metadata.AntiAffinity.mode:type_name -> metadata.AntiAffinityMode
	6,  // 2: metadata.HierarchyPolicies.anti_affinities:type_name -> metadata.AntiAffinity
	20, // 3: metadata.LoadBalancerPolicies.schedule_interval:type_name -> google.protobuf.Duration
	20, // 4: metadata.LoadBalancerPolicies.quarantine_time:type_name -> google.protobuf.Duration
	7,  // 5: metadata.Namespace.policies:type_name -> metadata.HierarchyPolicies
	5,  // 6: metadata.Cluster.data_servers:type_name -> metadata.DataServer
	9,  // 7: metadata.Cluster.namespaces:type_name -> metadata.Namespace
	7,  // 8: metadata.Cluster.policies:type_name -> metadata.HierarchyPolicies
	8,  // 9: metadata.Cluster.loadBalancer:type_name -> metadata.LoadBalancerPolicies
	4,  // 10: metadata.ShardSplittingState.phase:type_name -> metadata.SplitPhase
	17, // 11: metadata.ShardSplittingState.child_leaders_at_bootstrap:type_name -> metadata.ShardSplittingState.ChildLeadersAtBootstrapEntry
	3,  // 12: metadata.ShardState.status:type_name -> metadata.ShardStatus
	11, // 13: metadata.ShardState.int32_hash_range:type_name -> metadata.Int32HashRange
	12, // 14: metadata.ShardState.split:type_name -> metadata.ShardSplittingState
	18, // 15: metadata.NamespaceState.shards:type_name -> metadata.NamespaceState.ShardsEntry
	19, // 16: metadata.ClusterState.namespaces:type_name -> metadata.ClusterState.NamespacesEntry
	13, // 17: metadata.NamespaceState.ShardsEntry.value:type_name -> metadata.ShardState
	14, // 18: metadata.ClusterState.NamespacesEntry.value:type_name -> metadata.NamespaceState
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_metadata_proto_init() }
func file_metadata_proto_init() {
	if File_metadata_proto != nil {
		return
	}
	file_metadata_proto_msgTypes[2].OneofWrappers = []any{}
	file_metadata_proto_msgTypes[4].OneofWrappers = []any{}
	file_metadata_proto_msgTypes[5].OneofWrappers = []any{}
	file_metadata_proto_msgTypes[7].OneofWrappers = []any{}
	file_metadata_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metadata_proto_rawDesc), len(file_metadata_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metadata_proto_goTypes,
		DependencyIndexes: file_metadata_proto_depIdxs,
		EnumInfos:         file_metadata_proto_enumTypes,
		MessageInfos:      file_metadata_proto_msgTypes,
	}.Build()
	File_metadata_proto = out.File
	file_metadata_proto_goTypes = nil
	file_metadata_proto_depIdxs = nil
}
