// Copyright 2023-2026 The Oxia Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: storage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StorageEntry struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Value                 []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	VersionId             int64                  `protobuf:"varint,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	ModificationsCount    int64                  `protobuf:"varint,3,opt,name=modifications_count,json=modificationsCount,proto3" json:"modifications_count,omitempty"`
	CreationTimestamp     uint64                 `protobuf:"fixed64,4,opt,name=creation_timestamp,json=creationTimestamp,proto3" json:"creation_timestamp,omitempty"`
	ModificationTimestamp uint64                 `protobuf:"fixed64,5,opt,name=modification_timestamp,json=modificationTimestamp,proto3" json:"modification_timestamp,omitempty"`
	SessionId             *int64                 `protobuf:"varint,6,opt,name=session_id,json=sessionId,proto3,oneof" json:"session_id,omitempty"`
	ClientIdentity        *string                `protobuf:"bytes,7,opt,name=client_identity,json=clientIdentity,proto3,oneof" json:"client_identity,omitempty"`
	PartitionKey          *string                `protobuf:"bytes,8,opt,name=partition_key,json=partitionKey,proto3,oneof" json:"partition_key,omitempty"`
	SecondaryIndexes      []*SecondaryIndex      `protobuf:"bytes,9,rep,name=secondary_indexes,json=secondaryIndexes,proto3" json:"secondary_indexes,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *StorageEntry) Reset() {
	*x = StorageEntry{}
	mi := &file_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageEntry) ProtoMessage() {}

func (x *StorageEntry) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageEntry.ProtoReflect.Descriptor instead.
func (*StorageEntry) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{0}
}

func (x *StorageEntry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *StorageEntry) GetVersionId() int64 {
	if x != nil {
		return x.VersionId
	}
	return 0
}

func (x *StorageEntry) GetModificationsCount() int64 {
	if x != nil {
		return x.ModificationsCount
	}
	return 0
}

func (x *StorageEntry) GetCreationTimestamp() uint64 {
	if x != nil {
		return x.CreationTimestamp
	}
	return 0
}

func (x *StorageEntry) GetModificationTimestamp() uint64 {
	if x != nil {
		return x.ModificationTimestamp
	}
	return 0
}

func (x *StorageEntry) GetSessionId() int64 {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return 0
}

func (x *StorageEntry) GetClientIdentity() string {
	if x != nil && x.ClientIdentity != nil {
		return *x.ClientIdentity
	}
	return ""
}

func (x *StorageEntry) GetPartitionKey() string {
	if x != nil && x.PartitionKey != nil {
		return *x.PartitionKey
	}
	return ""
}

func (x *StorageEntry) GetSecondaryIndexes() []*SecondaryIndex {
	if x != nil {
		return x.SecondaryIndexes
	}
	return nil
}

type SessionMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeoutMs     uint32                 `protobuf:"varint,1,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Identity      string                 `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionMetadata) Reset() {
	*x = SessionMetadata{}
	mi := &file_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionMetadata) ProtoMessage() {}

func (x *SessionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionMetadata.ProtoReflect.Descriptor instead.
func (*SessionMetadata) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{1}
}

func (x *SessionMetadata) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *SessionMetadata) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type LogEntryValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*LogEntryValue_Requests
	//	*LogEntryValue_ControlRequest
	Value         isLogEntryValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntryValue) Reset() {
	*x = LogEntryValue{}
	mi := &file_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntryValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntryValue) ProtoMessage() {}

func (x *LogEntryValue) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntryValue.ProtoReflect.Descriptor instead.
func (*LogEntryValue) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{2}
}

func (x *LogEntryValue) GetValue() isLogEntryValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *LogEntryValue) GetRequests() *WriteRequests {
	if x != nil {
		if x, ok := x.Value.(*LogEntryValue_Requests); ok {
			return x.Requests
		}
	}
	return nil
}

func (x *LogEntryValue) GetControlRequest() *ControlRequest {
	if x != nil {
		if x, ok := x.Value.(*LogEntryValue_ControlRequest); ok {
			return x.ControlRequest
		}
	}
	return nil
}

type isLogEntryValue_Value interface {
	isLogEntryValue_Value()
}

type LogEntryValue_Requests struct {
	Requests *WriteRequests `protobuf:"bytes,1,opt,name=requests,proto3,oneof"`
}

type LogEntryValue_ControlRequest struct {
	ControlRequest *ControlRequest `protobuf:"bytes,2,opt,name=control_request,json=controlRequest,proto3,oneof"`
}

func (*LogEntryValue_Requests) isLogEntryValue_Value() {}

func (*LogEntryValue_ControlRequest) isLogEntryValue_Value() {}

type WriteRequests struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Writes        []*WriteRequest        `protobuf:"bytes,1,rep,name=writes,proto3" json:"writes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequests) Reset() {
	*x = WriteRequests{}
	mi := &file_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequests) ProtoMessage() {}

func (x *WriteRequests) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequests.ProtoReflect.Descriptor instead.
func (*WriteRequests) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{3}
}

func (x *WriteRequests) GetWrites() []*WriteRequest {
	if x != nil {
		return x.Writes
	}
	return nil
}

type ControlRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*ControlRequest_FeatureEnable
	//	*ControlRequest_RecordChecksum
	Value         isControlRequest_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlRequest) Reset() {
	*x = ControlRequest{}
	mi := &file_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlRequest) ProtoMessage() {}

func (x *ControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlRequest.ProtoReflect.Descriptor instead.
func (*ControlRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{4}
}

func (x *ControlRequest) GetValue() isControlRequest_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ControlRequest) GetFeatureEnable() *FeatureEnableRequest {
	if x != nil {
		if x, ok := x.Value.(*ControlRequest_FeatureEnable); ok {
			return x.FeatureEnable
		}
	}
	return nil
}

func (x *ControlRequest) GetRecordChecksum() *RecordChecksumRequest {
	if x != nil {
		if x, ok := x.Value.(*ControlRequest_RecordChecksum); ok {
			return x.RecordChecksum
		}
	}
	return nil
}

type isControlRequest_Value interface {
	isControlRequest_Value()
}

type ControlRequest_FeatureEnable struct {
	FeatureEnable *FeatureEnableRequest `protobuf:"bytes,1,opt,name=feature_enable,json=featureEnable,proto3,oneof"`
}

type ControlRequest_RecordChecksum struct {
	RecordChecksum *RecordChecksumRequest `protobuf:"bytes,2,opt,name=record_checksum,json=recordChecksum,proto3,oneof"`
}

func (*ControlRequest_FeatureEnable) isControlRequest_Value() {}

func (*ControlRequest_RecordChecksum) isControlRequest_Value() {}

type FeatureEnableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Features      []Feature              `protobuf:"varint,1,rep,packed,name=features,proto3,enum=replication.Feature" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureEnableRequest) Reset() {
	*x = FeatureEnableRequest{}
	mi := &file_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureEnableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureEnableRequest) ProtoMessage() {}

func (x *FeatureEnableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureEnableRequest.ProtoReflect.Descriptor instead.
func (*FeatureEnableRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{5}
}

func (x *FeatureEnableRequest) GetFeatures() []Feature {
	if x != nil {
		return x.Features
	}
	return nil
}

type RecordChecksumRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordChecksumRequest) Reset() {
	*x = RecordChecksumRequest{}
	mi := &file_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordChecksumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordChecksumRequest) ProtoMessage() {}

func (x *RecordChecksumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordChecksumRequest.ProtoReflect.Descriptor instead.
func (*RecordChecksumRequest) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{6}
}

// Wire-compatible twin of io.oxia.proto.v1.NotificationBatch: a protobuf map
// field is encoded identically to a repeated entry message (key = 1,
// value = 2), and repeated fields marshal in slice order — so marshaling the
// entries sorted by key with the generated vtproto code yields deterministic
// bytes, as required by the replicated batch checksum, without a hand-written
// marshaler. Must mirror NotificationBatch field-for-field; the byte-equality
// test in notifications_marshal_test.go fails on any drift.
type SortedNotificationBatch struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Shard         int64                     `protobuf:"varint,1,opt,name=shard,proto3" json:"shard,omitempty"`
	Offset        int64                     `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Timestamp     uint64                    `protobuf:"fixed64,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Notifications []*NotificationBatchEntry `protobuf:"bytes,4,rep,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortedNotificationBatch) Reset() {
	*x = SortedNotificationBatch{}
	mi := &file_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortedNotificationBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortedNotificationBatch) ProtoMessage() {}

func (x *SortedNotificationBatch) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortedNotificationBatch.ProtoReflect.Descriptor instead.
func (*SortedNotificationBatch) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{7}
}

func (x *SortedNotificationBatch) GetShard() int64 {
	if x != nil {
		return x.Shard
	}
	return 0
}

func (x *SortedNotificationBatch) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SortedNotificationBatch) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SortedNotificationBatch) GetNotifications() []*NotificationBatchEntry {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type NotificationBatchEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// optional: presence-tracked, so the field is emitted even for an empty
	// key, exactly as a map entry encodes it
	Key           *string       `protobuf:"bytes,1,opt,name=key,proto3,oneof" json:"key,omitempty"`
	Value         *Notification `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationBatchEntry) Reset() {
	*x = NotificationBatchEntry{}
	mi := &file_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationBatchEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationBatchEntry) ProtoMessage() {}

func (x *NotificationBatchEntry) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationBatchEntry.ProtoReflect.Descriptor instead.
func (*NotificationBatchEntry) Descriptor() ([]byte, []int) {
	return file_storage_proto_rawDescGZIP(), []int{8}
}

func (x *NotificationBatchEntry) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *NotificationBatchEntry) GetValue() *Notification {
	if x != nil {
		return x.Value
	}
	return nil
}

var file_storage_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         64101,
		Name:          "proto.mempool",
		Tag:           "varint,64101,opt,name=mempool",
		Filename:      "storage.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional bool mempool = 64101;
	E_Mempool = &file_storage_proto_extTypes[0]
)

var File_storage_proto protoreflect.FileDescriptor

const file_storage_proto_rawDesc = "" +
	"\n" +
	"\rstorage.proto\x12\x05proto\x1a\fclient.proto\x1a\x11replication.proto\x1a google/protobuf/descriptor.proto\"\xe0\x03\n" +
	"\fStorageEntry\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x1d\n" +
	"\n" +
	"version_id\x18\x02 \x01(\x03R\tversionId\x12/\n" +
	"\x13modifications_count\x18\x03 \x01(\x03R\x12modificationsCount\x12-\n" +
	"\x12creation_timestamp\x18\x04 \x01(\x06R\x11creationTimestamp\x125\n" +
	"\x16modification_timestamp\x18\x05 \x01(\x06R\x15modificationTimestamp\x12\"\n" +
	"\n" +
	"session_id\x18\x06 \x01(\x03H\x00R\tsessionId\x88\x01\x01\x12,\n" +
	"\x0fclient_identity\x18\a \x01(\tH\x01R\x0eclientIdentity\x88\x01\x01\x12(\n" +
	"\rpartition_key\x18\b \x01(\tH\x02R\fpartitionKey\x88\x01\x01\x12M\n" +
	"\x11secondary_indexes\x18\t \x03(\v2 .io.oxia.proto.v1.SecondaryIndexR\x10secondaryIndexes:\x04\xa8\xa6\x1f\x01B\r\n" +
	"\v_session_idB\x12\n" +
	"\x10_client_identityB\x10\n" +
	"\x0e_partition_key\"R\n" +
	"\x0fSessionMetadata\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x01 \x01(\rR\ttimeoutMs\x12\x1a\n" +
	"\bidentity\x18\x02 \x01(\tR\bidentity:\x04\xa8\xa6\x1f\x01\"\x94\x01\n" +
	"\rLogEntryValue\x122\n" +
	"\brequests\x18\x01 \x01(\v2\x14.proto.WriteRequestsH\x00R\brequests\x12@\n" +
	"\x0fcontrol_request\x18\x02 \x01(\v2\x15.proto.ControlRequestH\x00R\x0econtrolRequest:\x04\xa8\xa6\x1f\x01B\a\n" +
	"\x05value\"G\n" +
	"\rWriteRequests\x126\n" +
	"\x06writes\x18\x01 \x03(\v2\x1e.io.oxia.proto.v1.WriteRequestR\x06writes\"\xa8\x01\n" +
	"\x0eControlRequest\x12D\n" +
	"\x0efeature_enable\x18\x01 \x01(\v2\x1b.proto.FeatureEnableRequestH\x00R\rfeatureEnable\x12G\n" +
	"\x0frecord_checksum\x18\x02 \x01(\v2\x1c.proto.RecordChecksumRequestH\x00R\x0erecordChecksumB\a\n" +
	"\x05value\"H\n" +
	"\x14FeatureEnableRequest\x120\n" +
	"\bfeatures\x18\x01 \x03(\x0e2\x14.replication.FeatureR\bfeatures\"\x17\n" +
	"\x15RecordChecksumRequest\"\xaa\x01\n" +
	"\x17SortedNotificationBatch\x12\x14\n" +
	"\x05shard\x18\x01 \x01(\x03R\x05shard\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x06R\ttimestamp\x12C\n" +
	"\rnotifications\x18\x04 \x03(\v2\x1d.proto.NotificationBatchEntryR\rnotifications\"m\n" +
	"\x16NotificationBatchEntry\x12\x15\n" +
	"\x03key\x18\x01 \x01(\tH\x00R\x03key\x88\x01\x01\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.io.oxia.proto.v1.NotificationR\x05valueB\x06\n" +
	"\x04_key:>\n" +
	"\amempool\x12\x1f.google.protobuf.MessageOptions\x18\xe5\xf4\x03 \x01(\bR\amempool\x88\x01\x01B&Z$github.com/oxia-db/oxia/common/protob\x06proto3"

var (
	file_storage_proto_rawDescOnce sync.Once
	file_storage_proto_rawDescData []byte
)

func file_storage_proto_rawDescGZIP() []byte {
	file_storage_proto_rawDescOnce.Do(func() {
		file_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)))
	})
	return file_storage_proto_rawDescData
}

var file_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_storage_proto_goTypes = []any{
	(*StorageEntry)(nil),                // 0: proto.StorageEntry
	(*SessionMetadata)(nil),             // 1: proto.SessionMetadata
	(*LogEntryValue)(nil),               // 2: proto.LogEntryValue
	(*WriteRequests)(nil),               // 3: proto.WriteRequests
	(*ControlRequest)(nil),              // 4: proto.ControlRequest
	(*FeatureEnableRequest)(nil),        // 5: proto.FeatureEnableRequest
	(*RecordChecksumRequest)(nil),       // 6: proto.RecordChecksumRequest
	(*SortedNotificationBatch)(nil),     // 7: proto.SortedNotificationBatch
	(*NotificationBatchEntry)(nil),      // 8: proto.NotificationBatchEntry
	(*SecondaryIndex)(nil),              // 9: io.oxia.proto.v1.SecondaryIndex
	(*WriteRequest)(nil),                // 10: io.oxia.proto.v1.WriteRequest
	(Feature)(0),                        // 11: replication.Feature
	(*Notification)(nil),                // 12: io.oxia.proto.v1.Notification
	(*descriptorpb.MessageOptions)(nil), // 13: google.protobuf.MessageOptions
}
var file_storage_proto_depIdxs = []int32{
	9,  // 0: proto.StorageEntry.secondary_indexes:type_name -> io.oxia.proto.v1.SecondaryIndex
	3,  // 1: proto.LogEntryValue.requests:type_name -> proto.WriteRequests
	4,  // 2: proto.LogEntryValue.control_request:type_name -> proto.ControlRequest
	10, // 3: proto.WriteRequests.writes:type_name -> io.oxia.proto.v1.WriteRequest
	5,  // 4: proto.ControlRequest.feature_enable:type_name -> proto.FeatureEnableRequest
	6,  // 5: proto.ControlRequest.record_checksum:type_name -> proto.RecordChecksumRequest
	11, // 6: proto.FeatureEnableRequest.features:type_name -> replication.Feature
	8,  // 7: proto.SortedNotificationBatch.notifications:type_name -> proto.NotificationBatchEntry
	12, // 8: proto.NotificationBatchEntry.value:type_name -> io.oxia.proto.v1.Notification
	13, // 9: proto.mempool:extendee -> google.protobuf.MessageOptions
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	9,  // [9:10] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_storage_proto_init() }
func file_storage_proto_init() {
	if File_storage_proto != nil {
		return
	}
	file_client_proto_init()
	file_replication_proto_init()
	file_storage_proto_msgTypes[0].OneofWrappers = []any{}
	file_storage_proto_msgTypes[2].OneofWrappers = []any{
		(*LogEntryValue_Requests)(nil),
		(*LogEntryValue_ControlRequest)(nil),
	}
	file_storage_proto_msgTypes[4].OneofWrappers = []any{
		(*ControlRequest_FeatureEnable)(nil),
		(*ControlRequest_RecordChecksum)(nil),
	}
	file_storage_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_proto_rawDesc), len(file_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_storage_proto_goTypes,
		DependencyIndexes: file_storage_proto_depIdxs,
		MessageInfos:      file_storage_proto_msgTypes,
		ExtensionInfos:    file_storage_proto_extTypes,
	}.Build()
	File_storage_proto = out.File
	file_storage_proto_goTypes = nil
	file_storage_proto_depIdxs = nil
}
