# Copyright 2023 StreamNative, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: oxia.streamnative.io/v1alpha1
kind: OxiaCluster
metadata:
  labels:
    app.kubernetes.io/name: oxiacluster
    app.kubernetes.io/instance: oxiacluster-sample
    app.kubernetes.io/part-of: oxia-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: oxia-operator
  name: oxiacluster-sample
spec:
  namespaces:
    - name: default
      initialShardCount: 3
      replicationFactor: 3

  coordinator:
    cpu: 100m
    memory: 128Mi
  server:
    replicas: 3
    cpu: 1
    memory: 1Gi
    storage: 8Gi
    #storageClassName: xxx
  image:
    repository: streamnative/oxia
    tag: main
    pullPolicy: Always
    #pullSecrets: xxx
  pprofEnabled: false
  monitoringEnabled: true
