apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: oxiaclusters.oxia.streamnative.io
spec:
  group: oxia.streamnative.io
  names:
    kind: OxiaCluster
    singular: cluster
    plural: oxiaclusters
    shortNames: [ "oc" ]
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                shardCount:
                  type: integer
                replicationFactor:
                  type: integer
                serverReplicas:
                  type: integer
                serverResources:
                  type: object
                  properties:
                    cpu:
                      type: string
                    memory:
                      type: string
                serverVolume:
                  type: string
                coordinatorResources:
                  type: object
                  properties:
                    cpu:
                      type: string
                    memory:
                      type: string
                image:
                  type: string
                monitoringEnabled:
                  type: boolean
            status:
              type: object
              properties:
                shards:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                      status:
                        type: string
                      epoch:
                        type: integer
                      leader:
                        type: object
                        properties:
                          public:
                            type: string
                          internal:
                            type: string
                      ensemble:
                        type: array
                        items:
                          type: object
                          properties:
                            public:
                              type: string
                            internal:
                              type: string
                      hashRange:
                        type: object
                        properties:
                          min:
                            type: integer
                          max:
                            type: integer
      subresources:
        status: {}
