// Copyright 2023-2025 The Oxia Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//*
// OxiaClient

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: compat/client_grpc_sn.proto

package compat

import (
	context "context"
	proto "github.com/oxia-db/oxia/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OxiaClient_GetShardAssignments_FullMethodName = "/io.streamnative.oxia.proto.OxiaClient/GetShardAssignments"
	OxiaClient_Write_FullMethodName               = "/io.streamnative.oxia.proto.OxiaClient/Write"
	OxiaClient_WriteStream_FullMethodName         = "/io.streamnative.oxia.proto.OxiaClient/WriteStream"
	OxiaClient_Read_FullMethodName                = "/io.streamnative.oxia.proto.OxiaClient/Read"
	OxiaClient_List_FullMethodName                = "/io.streamnative.oxia.proto.OxiaClient/List"
	OxiaClient_RangeScan_FullMethodName           = "/io.streamnative.oxia.proto.OxiaClient/RangeScan"
	OxiaClient_GetSequenceUpdates_FullMethodName  = "/io.streamnative.oxia.proto.OxiaClient/GetSequenceUpdates"
	OxiaClient_GetNotifications_FullMethodName    = "/io.streamnative.oxia.proto.OxiaClient/GetNotifications"
	OxiaClient_CreateSession_FullMethodName       = "/io.streamnative.oxia.proto.OxiaClient/CreateSession"
	OxiaClient_KeepAlive_FullMethodName           = "/io.streamnative.oxia.proto.OxiaClient/KeepAlive"
	OxiaClient_CloseSession_FullMethodName        = "/io.streamnative.oxia.proto.OxiaClient/CloseSession"
)

// OxiaClientClient is the client API for OxiaClient service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// *
// This service definitions serves for compatibility purpose,
// so that an older client, using the gRPC service definition in
// namespace `io.streamnative.oxia.proto` can still talk to a newer
// Oxia server.
//
// Once all the old clients are upgraded, this will be removed.
type OxiaClientClient interface {
	GetShardAssignments(ctx context.Context, in *proto.ShardAssignmentsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[proto.ShardAssignments], error)
	Write(ctx context.Context, in *proto.WriteRequest, opts ...grpc.CallOption) (*proto.WriteResponse, error)
	WriteStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[proto.WriteRequest, proto.WriteResponse], error)
	Read(ctx context.Context, in *proto.ReadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[proto.ReadResponse], error)
	List(ctx context.Context, in *proto.ListRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[proto.ListResponse], error)
	RangeScan(ctx context.Context, in *proto.RangeScanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[proto.RangeScanResponse], error)
	GetSequenceUpdates(ctx context.Context, in *proto.GetSequenceUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[proto.GetSequenceUpdatesResponse], error)
	GetNotifications(ctx context.Context, in *proto.NotificationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[proto.NotificationBatch], error)
	CreateSession(ctx context.Context, in *proto.CreateSessionRequest, opts ...grpc.CallOption) (*proto.CreateSessionResponse, error)
	KeepAlive(ctx context.Context, in *proto.SessionHeartbeat, opts ...grpc.CallOption) (*proto.KeepAliveResponse, error)
	CloseSession(ctx context.Context, in *proto.CloseSessionRequest, opts ...grpc.CallOption) (*proto.CloseSessionResponse, error)
}

type oxiaClientClient struct {
	cc grpc.ClientConnInterface
}

func NewOxiaClientClient(cc grpc.ClientConnInterface) OxiaClientClient {
	return &oxiaClientClient{cc}
}

func (c *oxiaClientClient) GetShardAssignments(ctx context.Context, in *proto.ShardAssignmentsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[proto.ShardAssignments], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OxiaClient_ServiceDesc.Streams[0], OxiaClient_GetShardAssignments_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[proto.ShardAssignmentsRequest, proto.ShardAssignments]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OxiaClient_GetShardAssignmentsClient = grpc.ServerStreamingClient[proto.ShardAssignments]

func (c *oxiaClientClient) Write(ctx context.Context, in *proto.WriteRequest, opts ...grpc.CallOption) (*proto.WriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(proto.WriteResponse)
	err := c.cc.Invoke(ctx, OxiaClient_Write_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oxiaClientClient) WriteStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[proto.WriteRequest, proto.WriteResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OxiaClient_ServiceDesc.Streams[1], OxiaClient_WriteStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[proto.WriteRequest, proto.WriteResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OxiaClient_WriteStreamClient = grpc.BidiStreamingClient[proto.WriteRequest, proto.WriteResponse]

func (c *oxiaClientClient) Read(ctx context.Context, in *proto.ReadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[proto.ReadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OxiaClient_ServiceDesc.Streams[2], OxiaClient_Read_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[proto.ReadRequest, proto.ReadResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OxiaClient_ReadClient = grpc.ServerStreamingClient[proto.ReadResponse]

func (c *oxiaClientClient) List(ctx context.Context, in *proto.ListRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[proto.ListResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OxiaClient_ServiceDesc.Streams[3], OxiaClient_List_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[proto.ListRequest, proto.ListResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OxiaClient_ListClient = grpc.ServerStreamingClient[proto.ListResponse]

func (c *oxiaClientClient) RangeScan(ctx context.Context, in *proto.RangeScanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[proto.RangeScanResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OxiaClient_ServiceDesc.Streams[4], OxiaClient_RangeScan_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[proto.RangeScanRequest, proto.RangeScanResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OxiaClient_RangeScanClient = grpc.ServerStreamingClient[proto.RangeScanResponse]

func (c *oxiaClientClient) GetSequenceUpdates(ctx context.Context, in *proto.GetSequenceUpdatesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[proto.GetSequenceUpdatesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OxiaClient_ServiceDesc.Streams[5], OxiaClient_GetSequenceUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[proto.GetSequenceUpdatesRequest, proto.GetSequenceUpdatesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OxiaClient_GetSequenceUpdatesClient = grpc.ServerStreamingClient[proto.GetSequenceUpdatesResponse]

func (c *oxiaClientClient) GetNotifications(ctx context.Context, in *proto.NotificationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[proto.NotificationBatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OxiaClient_ServiceDesc.Streams[6], OxiaClient_GetNotifications_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[proto.NotificationsRequest, proto.NotificationBatch]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OxiaClient_GetNotificationsClient = grpc.ServerStreamingClient[proto.NotificationBatch]

func (c *oxiaClientClient) CreateSession(ctx context.Context, in *proto.CreateSessionRequest, opts ...grpc.CallOption) (*proto.CreateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(proto.CreateSessionResponse)
	err := c.cc.Invoke(ctx, OxiaClient_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oxiaClientClient) KeepAlive(ctx context.Context, in *proto.SessionHeartbeat, opts ...grpc.CallOption) (*proto.KeepAliveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(proto.KeepAliveResponse)
	err := c.cc.Invoke(ctx, OxiaClient_KeepAlive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oxiaClientClient) CloseSession(ctx context.Context, in *proto.CloseSessionRequest, opts ...grpc.CallOption) (*proto.CloseSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(proto.CloseSessionResponse)
	err := c.cc.Invoke(ctx, OxiaClient_CloseSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OxiaClientServer is the server API for OxiaClient service.
// All implementations must embed UnimplementedOxiaClientServer
// for forward compatibility.
//
// *
// This service definitions serves for compatibility purpose,
// so that an older client, using the gRPC service definition in
// namespace `io.streamnative.oxia.proto` can still talk to a newer
// Oxia server.
//
// Once all the old clients are upgraded, this will be removed.
type OxiaClientServer interface {
	GetShardAssignments(*proto.ShardAssignmentsRequest, grpc.ServerStreamingServer[proto.ShardAssignments]) error
	Write(context.Context, *proto.WriteRequest) (*proto.WriteResponse, error)
	WriteStream(grpc.BidiStreamingServer[proto.WriteRequest, proto.WriteResponse]) error
	Read(*proto.ReadRequest, grpc.ServerStreamingServer[proto.ReadResponse]) error
	List(*proto.ListRequest, grpc.ServerStreamingServer[proto.ListResponse]) error
	RangeScan(*proto.RangeScanRequest, grpc.ServerStreamingServer[proto.RangeScanResponse]) error
	GetSequenceUpdates(*proto.GetSequenceUpdatesRequest, grpc.ServerStreamingServer[proto.GetSequenceUpdatesResponse]) error
	GetNotifications(*proto.NotificationsRequest, grpc.ServerStreamingServer[proto.NotificationBatch]) error
	CreateSession(context.Context, *proto.CreateSessionRequest) (*proto.CreateSessionResponse, error)
	KeepAlive(context.Context, *proto.SessionHeartbeat) (*proto.KeepAliveResponse, error)
	CloseSession(context.Context, *proto.CloseSessionRequest) (*proto.CloseSessionResponse, error)
	mustEmbedUnimplementedOxiaClientServer()
}

// UnimplementedOxiaClientServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOxiaClientServer struct{}

func (UnimplementedOxiaClientServer) GetShardAssignments(*proto.ShardAssignmentsRequest, grpc.ServerStreamingServer[proto.ShardAssignments]) error {
	return status.Errorf(codes.Unimplemented, "method GetShardAssignments not implemented")
}
func (UnimplementedOxiaClientServer) Write(context.Context, *proto.WriteRequest) (*proto.WriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedOxiaClientServer) WriteStream(grpc.BidiStreamingServer[proto.WriteRequest, proto.WriteResponse]) error {
	return status.Errorf(codes.Unimplemented, "method WriteStream not implemented")
}
func (UnimplementedOxiaClientServer) Read(*proto.ReadRequest, grpc.ServerStreamingServer[proto.ReadResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedOxiaClientServer) List(*proto.ListRequest, grpc.ServerStreamingServer[proto.ListResponse]) error {
	return status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedOxiaClientServer) RangeScan(*proto.RangeScanRequest, grpc.ServerStreamingServer[proto.RangeScanResponse]) error {
	return status.Errorf(codes.Unimplemented, "method RangeScan not implemented")
}
func (UnimplementedOxiaClientServer) GetSequenceUpdates(*proto.GetSequenceUpdatesRequest, grpc.ServerStreamingServer[proto.GetSequenceUpdatesResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetSequenceUpdates not implemented")
}
func (UnimplementedOxiaClientServer) GetNotifications(*proto.NotificationsRequest, grpc.ServerStreamingServer[proto.NotificationBatch]) error {
	return status.Errorf(codes.Unimplemented, "method GetNotifications not implemented")
}
func (UnimplementedOxiaClientServer) CreateSession(context.Context, *proto.CreateSessionRequest) (*proto.CreateSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedOxiaClientServer) KeepAlive(context.Context, *proto.SessionHeartbeat) (*proto.KeepAliveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeepAlive not implemented")
}
func (UnimplementedOxiaClientServer) CloseSession(context.Context, *proto.CloseSessionRequest) (*proto.CloseSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseSession not implemented")
}
func (UnimplementedOxiaClientServer) mustEmbedUnimplementedOxiaClientServer() {}
func (UnimplementedOxiaClientServer) testEmbeddedByValue()                    {}

// UnsafeOxiaClientServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OxiaClientServer will
// result in compilation errors.
type UnsafeOxiaClientServer interface {
	mustEmbedUnimplementedOxiaClientServer()
}

func RegisterOxiaClientServer(s grpc.ServiceRegistrar, srv OxiaClientServer) {
	// If the following call pancis, it indicates UnimplementedOxiaClientServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OxiaClient_ServiceDesc, srv)
}

func _OxiaClient_GetShardAssignments_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(proto.ShardAssignmentsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OxiaClientServer).GetShardAssignments(m, &grpc.GenericServerStream[proto.ShardAssignmentsRequest, proto.ShardAssignments]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OxiaClient_GetShardAssignmentsServer = grpc.ServerStreamingServer[proto.ShardAssignments]

func _OxiaClient_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto.WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OxiaClientServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OxiaClient_Write_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OxiaClientServer).Write(ctx, req.(*proto.WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OxiaClient_WriteStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OxiaClientServer).WriteStream(&grpc.GenericServerStream[proto.WriteRequest, proto.WriteResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OxiaClient_WriteStreamServer = grpc.BidiStreamingServer[proto.WriteRequest, proto.WriteResponse]

func _OxiaClient_Read_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(proto.ReadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OxiaClientServer).Read(m, &grpc.GenericServerStream[proto.ReadRequest, proto.ReadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OxiaClient_ReadServer = grpc.ServerStreamingServer[proto.ReadResponse]

func _OxiaClient_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(proto.ListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OxiaClientServer).List(m, &grpc.GenericServerStream[proto.ListRequest, proto.ListResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OxiaClient_ListServer = grpc.ServerStreamingServer[proto.ListResponse]

func _OxiaClient_RangeScan_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(proto.RangeScanRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OxiaClientServer).RangeScan(m, &grpc.GenericServerStream[proto.RangeScanRequest, proto.RangeScanResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OxiaClient_RangeScanServer = grpc.ServerStreamingServer[proto.RangeScanResponse]

func _OxiaClient_GetSequenceUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(proto.GetSequenceUpdatesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OxiaClientServer).GetSequenceUpdates(m, &grpc.GenericServerStream[proto.GetSequenceUpdatesRequest, proto.GetSequenceUpdatesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OxiaClient_GetSequenceUpdatesServer = grpc.ServerStreamingServer[proto.GetSequenceUpdatesResponse]

func _OxiaClient_GetNotifications_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(proto.NotificationsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OxiaClientServer).GetNotifications(m, &grpc.GenericServerStream[proto.NotificationsRequest, proto.NotificationBatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OxiaClient_GetNotificationsServer = grpc.ServerStreamingServer[proto.NotificationBatch]

func _OxiaClient_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto.CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OxiaClientServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OxiaClient_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OxiaClientServer).CreateSession(ctx, req.(*proto.CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OxiaClient_KeepAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto.SessionHeartbeat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OxiaClientServer).KeepAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OxiaClient_KeepAlive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OxiaClientServer).KeepAlive(ctx, req.(*proto.SessionHeartbeat))
	}
	return interceptor(ctx, in, info, handler)
}

func _OxiaClient_CloseSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto.CloseSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OxiaClientServer).CloseSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OxiaClient_CloseSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OxiaClientServer).CloseSession(ctx, req.(*proto.CloseSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OxiaClient_ServiceDesc is the grpc.ServiceDesc for OxiaClient service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OxiaClient_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "io.streamnative.oxia.proto.OxiaClient",
	HandlerType: (*OxiaClientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Write",
			Handler:    _OxiaClient_Write_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _OxiaClient_CreateSession_Handler,
		},
		{
			MethodName: "KeepAlive",
			Handler:    _OxiaClient_KeepAlive_Handler,
		},
		{
			MethodName: "CloseSession",
			Handler:    _OxiaClient_CloseSession_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetShardAssignments",
			Handler:       _OxiaClient_GetShardAssignments_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WriteStream",
			Handler:       _OxiaClient_WriteStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Read",
			Handler:       _OxiaClient_Read_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "List",
			Handler:       _OxiaClient_List_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RangeScan",
			Handler:       _OxiaClient_RangeScan_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetSequenceUpdates",
			Handler:       _OxiaClient_GetSequenceUpdates_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetNotifications",
			Handler:       _OxiaClient_GetNotifications_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "compat/client_grpc_sn.proto",
}
