apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: oxiaclusters.oxia.streamnative.io
spec:
  group: oxia.streamnative.io
  names:
    kind: OxiaCluster
    singular: oxiacluster
    plural: oxiaclusters
    shortNames: [ "oc" ]
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                serverReplicas:
                  type: integer
                shardCount:
                  type: integer
                replicationFactor:
                  type: integer
            status:
              type: object
              properties:
                shards:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                      status:
                        type: string
                      epoch:
                        type: integer
                      leader:
                        type: object
                        properties:
                          public:
                            type: string
                          internal:
                            type: string
                      ensemble:
                        type: array
                        items:
                          type: object
                          properties:
                            public:
                              type: string
                            internal:
                              type: string
                      hashRange:
                        type: object
                        properties:
                          min:
                            type: integer
                          max:
                            type: integer
      subresources:
        status: {}
---
apiVersion: oxia.streamnative.io/v1alpha1
kind: OxiaCluster
metadata:
  name: oxia
  namespace: oxia
spec:
  serverReplicas: 1
  shardCount: 1
  replicationFactor: 1
status:
  shards:
    - id: 0
      status: Unknown # or SteadyState/Election
      epoch: 1670403094
      leader:
        public: oxia-server-0:6648
        internal: oxia-server-0:6649
      ensemble:
        - public: oxia-server-0:6648
          internal: oxia-server-0:6649
        - public: oxia-server-1:6648
          internal: oxia-server-1:6649
        - public: oxia-server-2:6648
          internal: oxia-server-2:6649
      hashRange:
        min: 0
        max: 4294967295
