apiVersion: oxia.streamnative.io/v1alpha1
kind: OxiaCluster
metadata:
  name: oxia
  namespace: oxia
spec:
  initialShardCount: 3
  replicationFactor: 3
  serverReplicas: 3
  serverResources:
    cpu: 100m
    memory: 128Mi
  serverVolume: 1Gi
  coordinatorResources:
    cpu: 100m
    memory: 128Mi
  image: streamnative/oxia:main
  imagePullPolicy: Always
  monitoringEnabled: true
