{
 "title": "Oxia - Containers Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(oxia_coordinator_node_running, oxia_cluster)"
    }
   },
   {
    "name": "k8s_namespace",
    "label": "namespace",
    "query": {
     "query": "process_resident_memory_bytes{oxia_cluster=~\"$cluster\"}"
    }
   },
   {
    "name": "component",
    "label": "Component",
    "query": {
     "query": "grpc_server_handled_total{oxia_cluster=~\"$cluster\"}"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "process_cpu_seconds_total{oxia_cluster=~\"$cluster\", app_kubernetes_io_component=~\"$component\", kubernetes_namespace=~\"$k8s_namespace\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "pod",
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(   rate(container_cpu_user_seconds_total{namespace=~\"$namespace\", pod=~\"$pod\", container !=\"\"}[5m])) by (pod)",
     "legendFormat": "user"
    },
    {
     "expr": "100 * sum(   rate(container_cpu_cfs_throttled_seconds_total{namespace!~\"kube-system\", pod=\"$pod\", container!=\"\"}[5m])) by (pod)",
     "legendFormat": "throttled"
    },
    {
     "expr": "100 * sum(rate(container_cpu_system_seconds_total{namespace!~\"kube-system\", pod=\"$pod\", container !=\"\"}[5m])) by (pod)",
     "legendFormat": "system"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "container_spec_memory_limit_bytes = 0 mean no resource limits configured for this container.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{namespace=~\"$k8s_namespace\", pod=\"$pod\", container!=\"\"})",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(container_memory_swap{namespace=~\"$k8s_namespace\", pod=\"$pod\", container!=\"\"}) by (pod)",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{namespace=~\"$k8s_namespace\", pod=\"$pod\", container!~\"(|POD|istio-proxy)\"}) by (pod)",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(container_spec_memory_reservation_limit_bytes{namespace=~\"$k8s_namespace\", pod=\"$pod\", container!=\"\"}) by (pod)",
     "legendFormat": "Reserved"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$k8s_namespace\", pod=\"$pod\", container!=\"\"}) by (pod)",
     "legendFormat": "Working_set"
    },
    {
     "expr": "sum(container_memory_cache{namespace=~\"$k8s_namespace\", pod=\"$pod\", container!=\"\"}) by (pod)",
     "legendFormat": "Cache"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * sum(rate(container_network_receive_bytes_total{namespace=~\"$k8s_namespace\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "In"
    },
    {
     "expr": "- 8 * sum(rate(container_network_transmit_bytes_total{namespace=~\"$k8s_namespace\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=~\"$k8s_namespace\", pod=~\"$pod\", container!=\"\"}[5m])) by (pod,device)",
     "legendFormat": "Writes {{ device }}"
    },
    {
     "expr": "- sum(rate(container_fs_reads_bytes_total{namespace=~\"$k8s_namespace\", pod=~\"$pod\", container!=\"\"}[5m])) by (pod,device)",
     "legendFormat": "Reads {{ device }}"
    }
   ]
  }
 ]
}