{
 "title": "Oxia - Nodes",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DataSource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Oxia Cluster",
    "query": {
     "query": "label_values(oxia_coordinator_node_running, oxia_cluster)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "oxia_server_wal_entries{oxia_cluster=~\"$cluster\"}"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "oxia_server_wal_entries{oxia_cluster=~\"$cluster\", kubernetes_pod_name=~\"$pod\"}"
    }
   },
   {
    "name": "shard",
    "label": "Shard",
    "query": {
     "query": "oxia_server_wal_entries{oxia_cluster=~\"$cluster\", kubernetes_pod_name=~\"$pod\", oxia_namespace=~\"$namespace\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Write ops/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum(\n      rate(oxia_server_db_puts_total{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}[1m])\n    + rate(oxia_server_db_gets_total{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}[1m])\n    + rate(oxia_server_db_lists_total{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}[1m])\n    + rate(oxia_server_db_deletes_total{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}[1m])\n    + rate(oxia_server_db_delete_ranges_total{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}[1m])\n) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Write Batch ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum(rate(oxia_server_leader_write_latency_milliseconds_count{oxia_cluster=~\"$cluster\",  oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}[1m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Put ops/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum(rate(oxia_server_db_puts_total{oxia_cluster=~\"$cluster\",  oxia_namespace=~\"$namespace\",shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}[1m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Get ops/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum(rate(oxia_server_db_gets_total{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\",shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}[1m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Deletes ops/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum(rate(oxia_server_db_deletes_total{oxia_cluster=~\"$cluster\",  oxia_namespace=~\"$namespace\",shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}[1m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "List ops/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum(rate(oxia_server_db_lists_total{oxia_cluster=~\"$cluster\",  oxia_namespace=~\"$namespace\",shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}[1m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Delete Range ops/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum(rate(oxia_server_db_delete_ranges_total{oxia_cluster=~\"$cluster\",  oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}[1m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Write Batch Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Write Batch Latency 50pct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le, kubernetes_pod_name) \n(oxia_server_leader_write_latency_milliseconds_bucket{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\",  shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Write Batch Latency 95pct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, kubernetes_pod_name) \n(oxia_server_leader_write_latency_milliseconds_bucket{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Write Batch Latency 99pct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, kubernetes_pod_name) \n(oxia_server_leader_write_latency_milliseconds_bucket{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Write Batch Latency 99.9pct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum by (le, kubernetes_pod_name) \n(oxia_server_leader_write_latency_milliseconds_bucket{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Write Ahead Log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Append entry ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum(rate(oxia_server_wal_append_latency_milliseconds_count{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}[1m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Append entry Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(oxia_server_wal_append_bytes_total{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}[1m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Read entry ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(rate(oxia_server_wal_read_latency_milliseconds_count{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}[1m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Read entry bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(oxia_server_wal_read_bytes_total{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}[1m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "WAL append latency 50pct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le, kubernetes_pod_name) \n(oxia_server_wal_append_latency_milliseconds_bucket{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "WAL append latency 95pct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, kubernetes_pod_name) \n(oxia_server_wal_append_latency_milliseconds_bucket{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\",  shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "WAL append latency 99pct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, kubernetes_pod_name) \n(oxia_server_wal_append_latency_milliseconds_bucket{oxia_cluster=~\"$cluster\",oxia_namespace=~\"$namespace\",  shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "WAL append latency 99.9pct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum by (le, kubernetes_pod_name) \n(oxia_server_wal_append_latency_milliseconds_bucket{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "WAL fsync rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(oxia_server_wal_sync_latency_milliseconds_count{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}[1m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "WAL fsync latency 50pct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le, kubernetes_pod_name) \n(oxia_server_wal_sync_latency_milliseconds_bucket{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "WAL fsync latency 95pct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, kubernetes_pod_name) \n(oxia_server_wal_sync_latency_milliseconds_bucket{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "WAL fsync latency 99pct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, kubernetes_pod_name) \n(oxia_server_wal_sync_latency_milliseconds_bucket{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "WAL fsync latency 99.9pct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum by (le, kubernetes_pod_name) \n(oxia_server_wal_sync_latency_milliseconds_bucket{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "WAL read latency 50pct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le, kubernetes_pod_name) \n(oxia_server_wal_read_latency_milliseconds_bucket{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "WAL read latency 95pct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, kubernetes_pod_name) \n(oxia_server_wal_read_latency_milliseconds_bucket{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "WAL read latency 99pct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, kubernetes_pod_name) \n(oxia_server_wal_read_latency_milliseconds_bucket{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "WAL read latency 99.9pct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum by (le, kubernetes_pod_name) \n(oxia_server_wal_read_latency_milliseconds_bucket{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Number of entries in WAL",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(oxia_server_wal_entries{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "DB Write ops",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum(rate(oxia_server_kv_write_ops_total{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}[1m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "DB Write bytes/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(oxia_server_kv_write_bytes_total{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\",  shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}[1m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "DB Batch Commit Latency 50pct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le, kubernetes_pod_name) \n(oxia_server_kv_batch_commit_latency_milliseconds_bucket{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "DB Batch Commit Latency 95pct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, kubernetes_pod_name) \n(oxia_server_kv_batch_commit_latency_milliseconds_bucket{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "DB Batch Commit Latency 99pct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, kubernetes_pod_name) \n(oxia_server_kv_batch_commit_latency_milliseconds_bucket{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "DB Batch Commit Latency 99.9pct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum by (le, kubernetes_pod_name) \n(oxia_server_kv_batch_commit_latency_milliseconds_bucket{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "DB Batch - Keys count - 50pct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le, kubernetes_pod_name) \n(oxia_server_kv_batch_count_bucket{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "DB Batch - Keys count - 95pct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, pod) \n(oxia_server_kv_batch_count_bucket{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "DB Batch - Keys count - 99pct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, pod) \n(oxia_server_kv_batch_count_bucket{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "DB Batch - Keys count - 99.9pct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum by (le, pod) \n(oxia_server_kv_batch_count_bucket{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "DB Batch - Bytes size - 50pct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le, kubernetes_pod_name) \n(oxia_server_kv_batch_size_bytes_bucket{oxia_cluster=~\"$cluster\",oxia_namespace=~\"$namespace\",  shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "DB Batch - Bytes size - 95pct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, kubernetes_pod_name) \n(oxia_server_kv_batch_size_bytes_bucket{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "DB Batch - Bytes size - 99pct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, kubernetes_pod_name) \n(oxia_server_kv_batch_size_bytes_bucket{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "DB Batch - Bytes size - 99.9pct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum by (le, kubernetes_pod_name) \n(oxia_server_kv_batch_size_bytes_bucket{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Database - Pebble", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "Block Cache Hit rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(oxia_server_kv_pebble_block_cache_hits{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}[1m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Block Cache Miss rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(oxia_server_kv_pebble_block_cache_misses{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}[1m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Block Cache - Hit ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n    increase(oxia_server_kv_pebble_block_cache_hits{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}[1m])\n    / \n    ( increase(oxia_server_kv_pebble_block_cache_hits{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}[1m])\n     +\n      increase(oxia_server_kv_pebble_block_cache_misses{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}[1m])\n    )\n    \n) \nby (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Block Cache - Size ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(oxia_server_kv_pebble_block_cache_used_bytes{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "DB size on disk",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(oxia_server_kv_pebble_disk_space_bytes{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "DB - files count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(oxia_server_kv_pebble_num_files_total{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "DB - files count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(oxia_server_kv_pebble_num_files_total{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "DB Flush rate bytes/s",
   "type": "timeseries",
   "description": "The total amount of bytes flushed into the db",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(oxia_server_kv_pebble_flush_bytes{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}[1m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "MemTable size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(oxia_server_kv_pebble_memtable_size_bytes{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Compactions per min",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(oxia_server_kv_pebble_compactions_total{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}[1m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Compaction Debt",
   "type": "timeseries",
   "description": "The estimated number of bytes that need to be compacted",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(oxia_server_kv_pebble_compaction_debt_bytes{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "DB read rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(oxia_server_kv_pebble_read_bytes{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}[1m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Open Read Iterators",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(oxia_server_kv_pebble_read_iterators{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Read Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(oxia_server_kv_read_errors_total{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\", kubernetes_pod_name=~\"$pod\"}[1m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}