// Copyright 2023-2025 The Oxia Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//*
// OxiaClient

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: compat/client_grpc_sn.proto

package compat

import (
	proto "github.com/oxia-db/oxia/common/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_compat_client_grpc_sn_proto protoreflect.FileDescriptor

const file_compat_client_grpc_sn_proto_rawDesc = "" +
	"\n" +
	"\x1bcompat/client_grpc_sn.proto\x12\x1aio.streamnative.oxia.proto\x1a\fclient.proto2\xe9\a\n" +
	"\n" +
	"OxiaClient\x12f\n" +
	"\x13GetShardAssignments\x12).io.oxia.proto.v1.ShardAssignmentsRequest\x1a\".io.oxia.proto.v1.ShardAssignments0\x01\x12H\n" +
	"\x05Write\x12\x1e.io.oxia.proto.v1.WriteRequest\x1a\x1f.io.oxia.proto.v1.WriteResponse\x12R\n" +
	"\vWriteStream\x12\x1e.io.oxia.proto.v1.WriteRequest\x1a\x1f.io.oxia.proto.v1.WriteResponse(\x010\x01\x12G\n" +
	"\x04Read\x12\x1d.io.oxia.proto.v1.ReadRequest\x1a\x1e.io.oxia.proto.v1.ReadResponse0\x01\x12G\n" +
	"\x04List\x12\x1d.io.oxia.proto.v1.ListRequest\x1a\x1e.io.oxia.proto.v1.ListResponse0\x01\x12V\n" +
	"\tRangeScan\x12\".io.oxia.proto.v1.RangeScanRequest\x1a#.io.oxia.proto.v1.RangeScanResponse0\x01\x12q\n" +
	"\x12GetSequenceUpdates\x12+.io.oxia.proto.v1.GetSequenceUpdatesRequest\x1a,.io.oxia.proto.v1.GetSequenceUpdatesResponse0\x01\x12a\n" +
	"\x10GetNotifications\x12&.io.oxia.proto.v1.NotificationsRequest\x1a#.io.oxia.proto.v1.NotificationBatch0\x01\x12`\n" +
	"\rCreateSession\x12&.io.oxia.proto.v1.CreateSessionRequest\x1a'.io.oxia.proto.v1.CreateSessionResponse\x12T\n" +
	"\tKeepAlive\x12\".io.oxia.proto.v1.SessionHeartbeat\x1a#.io.oxia.proto.v1.KeepAliveResponse\x12]\n" +
	"\fCloseSession\x12%.io.oxia.proto.v1.CloseSessionRequest\x1a&.io.oxia.proto.v1.CloseSessionResponseB/P\x01Z+github.com/oxia-db/oxia/common/proto/compatb\x06proto3"

var file_compat_client_grpc_sn_proto_goTypes = []any{
	(*proto.ShardAssignmentsRequest)(nil),    // 0: io.oxia.proto.v1.ShardAssignmentsRequest
	(*proto.WriteRequest)(nil),               // 1: io.oxia.proto.v1.WriteRequest
	(*proto.ReadRequest)(nil),                // 2: io.oxia.proto.v1.ReadRequest
	(*proto.ListRequest)(nil),                // 3: io.oxia.proto.v1.ListRequest
	(*proto.RangeScanRequest)(nil),           // 4: io.oxia.proto.v1.RangeScanRequest
	(*proto.GetSequenceUpdatesRequest)(nil),  // 5: io.oxia.proto.v1.GetSequenceUpdatesRequest
	(*proto.NotificationsRequest)(nil),       // 6: io.oxia.proto.v1.NotificationsRequest
	(*proto.CreateSessionRequest)(nil),       // 7: io.oxia.proto.v1.CreateSessionRequest
	(*proto.SessionHeartbeat)(nil),           // 8: io.oxia.proto.v1.SessionHeartbeat
	(*proto.CloseSessionRequest)(nil),        // 9: io.oxia.proto.v1.CloseSessionRequest
	(*proto.ShardAssignments)(nil),           // 10: io.oxia.proto.v1.ShardAssignments
	(*proto.WriteResponse)(nil),              // 11: io.oxia.proto.v1.WriteResponse
	(*proto.ReadResponse)(nil),               // 12: io.oxia.proto.v1.ReadResponse
	(*proto.ListResponse)(nil),               // 13: io.oxia.proto.v1.ListResponse
	(*proto.RangeScanResponse)(nil),          // 14: io.oxia.proto.v1.RangeScanResponse
	(*proto.GetSequenceUpdatesResponse)(nil), // 15: io.oxia.proto.v1.GetSequenceUpdatesResponse
	(*proto.NotificationBatch)(nil),          // 16: io.oxia.proto.v1.NotificationBatch
	(*proto.CreateSessionResponse)(nil),      // 17: io.oxia.proto.v1.CreateSessionResponse
	(*proto.KeepAliveResponse)(nil),          // 18: io.oxia.proto.v1.KeepAliveResponse
	(*proto.CloseSessionResponse)(nil),       // 19: io.oxia.proto.v1.CloseSessionResponse
}
var file_compat_client_grpc_sn_proto_depIdxs = []int32{
	0,  // 0: io.streamnative.oxia.proto.OxiaClient.GetShardAssignments:input_type -> io.oxia.proto.v1.ShardAssignmentsRequest
	1,  // 1: io.streamnative.oxia.proto.OxiaClient.Write:input_type -> io.oxia.proto.v1.WriteRequest
	1,  // 2: io.streamnative.oxia.proto.OxiaClient.WriteStream:input_type -> io.oxia.proto.v1.WriteRequest
	2,  // 3: io.streamnative.oxia.proto.OxiaClient.Read:input_type -> io.oxia.proto.v1.ReadRequest
	3,  // 4: io.streamnative.oxia.proto.OxiaClient.List:input_type -> io.oxia.proto.v1.ListRequest
	4,  // 5: io.streamnative.oxia.proto.OxiaClient.RangeScan:input_type -> io.oxia.proto.v1.RangeScanRequest
	5,  // 6: io.streamnative.oxia.proto.OxiaClient.GetSequenceUpdates:input_type -> io.oxia.proto.v1.GetSequenceUpdatesRequest
	6,  // 7: io.streamnative.oxia.proto.OxiaClient.GetNotifications:input_type -> io.oxia.proto.v1.NotificationsRequest
	7,  // 8: io.streamnative.oxia.proto.OxiaClient.CreateSession:input_type -> io.oxia.proto.v1.CreateSessionRequest
	8,  // 9: io.streamnative.oxia.proto.OxiaClient.KeepAlive:input_type -> io.oxia.proto.v1.SessionHeartbeat
	9,  // 10: io.streamnative.oxia.proto.OxiaClient.CloseSession:input_type -> io.oxia.proto.v1.CloseSessionRequest
	10, // 11: io.streamnative.oxia.proto.OxiaClient.GetShardAssignments:output_type -> io.oxia.proto.v1.ShardAssignments
	11, // 12: io.streamnative.oxia.proto.OxiaClient.Write:output_type -> io.oxia.proto.v1.WriteResponse
	11, // 13: io.streamnative.oxia.proto.OxiaClient.WriteStream:output_type -> io.oxia.proto.v1.WriteResponse
	12, // 14: io.streamnative.oxia.proto.OxiaClient.Read:output_type -> io.oxia.proto.v1.ReadResponse
	13, // 15: io.streamnative.oxia.proto.OxiaClient.List:output_type -> io.oxia.proto.v1.ListResponse
	14, // 16: io.streamnative.oxia.proto.OxiaClient.RangeScan:output_type -> io.oxia.proto.v1.RangeScanResponse
	15, // 17: io.streamnative.oxia.proto.OxiaClient.GetSequenceUpdates:output_type -> io.oxia.proto.v1.GetSequenceUpdatesResponse
	16, // 18: io.streamnative.oxia.proto.OxiaClient.GetNotifications:output_type -> io.oxia.proto.v1.NotificationBatch
	17, // 19: io.streamnative.oxia.proto.OxiaClient.CreateSession:output_type -> io.oxia.proto.v1.CreateSessionResponse
	18, // 20: io.streamnative.oxia.proto.OxiaClient.KeepAlive:output_type -> io.oxia.proto.v1.KeepAliveResponse
	19, // 21: io.streamnative.oxia.proto.OxiaClient.CloseSession:output_type -> io.oxia.proto.v1.CloseSessionResponse
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_compat_client_grpc_sn_proto_init() }
func file_compat_client_grpc_sn_proto_init() {
	if File_compat_client_grpc_sn_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_compat_client_grpc_sn_proto_rawDesc), len(file_compat_client_grpc_sn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_compat_client_grpc_sn_proto_goTypes,
		DependencyIndexes: file_compat_client_grpc_sn_proto_depIdxs,
	}.Build()
	File_compat_client_grpc_sn_proto = out.File
	file_compat_client_grpc_sn_proto_goTypes = nil
	file_compat_client_grpc_sn_proto_depIdxs = nil
}
