# permissions for end users to view oxiaclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: oxiacluster-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: oxia-operator
    app.kubernetes.io/part-of: oxia-operator
    app.kubernetes.io/managed-by: kustomize
  name: oxiacluster-viewer-role
rules:
- apiGroups:
  - oxia.io.streamnative
  resources:
  - oxiaclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - oxia.io.streamnative
  resources:
  - oxiaclusters/status
  verbs:
  - get
